// <auto-generated>
/*
 * Gladia Control API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections.Generic;
using System.Net;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text.Json;
using Gladia.SDK.Client;
using System.Diagnostics.CodeAnalysis;

namespace Gladia.SDK.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// This class is registered as transient.
    /// </summary>
    public interface ITranscriptionV1Api : IApi
    {
        /// <summary>
        /// The class containing the events
        /// </summary>
        TranscriptionV1ApiEvents Events { get; }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="audio"> (optional)</param>
        /// <param name="audioUrl"> (optional, default to &quot;http://files.gladia.io/example/audio-transcription/split_infinity.wav&quot;)</param>
        /// <param name="languageBehaviour"> (optional, default to automatic single language)</param>
        /// <param name="language"> (optional)</param>
        /// <param name="transcriptionHint"> (optional)</param>
        /// <param name="toggleDiarization"> (optional, default to false)</param>
        /// <param name="diarizationNumSpeakers"> (optional)</param>
        /// <param name="diarizationMinSpeakers"> (optional)</param>
        /// <param name="diarizationMaxSpeakers"> (optional)</param>
        /// <param name="toggleDirectTranslate"> (optional, default to false)</param>
        /// <param name="targetTranslationLanguage"> (optional)</param>
        /// <param name="outputFormat"> (optional, default to json)</param>
        /// <param name="toggleNoiseReduction"> (optional, default to false)</param>
        /// <param name="toggleAccurateWordsTimestamps"> (optional, default to false)</param>
        /// <param name="webhookUrl"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IAudioToTextControllerAudioTranscriptionApiResponse"/>&gt;</returns>
        Task<IAudioToTextControllerAudioTranscriptionApiResponse> AudioToTextControllerAudioTranscriptionAsync(Option<System.IO.Stream> audio = default, Option<string> audioUrl = default, Option<string> languageBehaviour = default, Option<string> language = default, Option<string> transcriptionHint = default, Option<bool> toggleDiarization = default, Option<int> diarizationNumSpeakers = default, Option<int> diarizationMinSpeakers = default, Option<int> diarizationMaxSpeakers = default, Option<bool> toggleDirectTranslate = default, Option<string> targetTranslationLanguage = default, Option<string> outputFormat = default, Option<bool> toggleNoiseReduction = default, Option<bool> toggleAccurateWordsTimestamps = default, Option<string> webhookUrl = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <param name="audio"> (optional)</param>
        /// <param name="audioUrl"> (optional, default to &quot;http://files.gladia.io/example/audio-transcription/split_infinity.wav&quot;)</param>
        /// <param name="languageBehaviour"> (optional, default to automatic single language)</param>
        /// <param name="language"> (optional)</param>
        /// <param name="transcriptionHint"> (optional)</param>
        /// <param name="toggleDiarization"> (optional, default to false)</param>
        /// <param name="diarizationNumSpeakers"> (optional)</param>
        /// <param name="diarizationMinSpeakers"> (optional)</param>
        /// <param name="diarizationMaxSpeakers"> (optional)</param>
        /// <param name="toggleDirectTranslate"> (optional, default to false)</param>
        /// <param name="targetTranslationLanguage"> (optional)</param>
        /// <param name="outputFormat"> (optional, default to json)</param>
        /// <param name="toggleNoiseReduction"> (optional, default to false)</param>
        /// <param name="toggleAccurateWordsTimestamps"> (optional, default to false)</param>
        /// <param name="webhookUrl"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IAudioToTextControllerAudioTranscriptionApiResponse"/>?&gt;</returns>
        Task<IAudioToTextControllerAudioTranscriptionApiResponse?> AudioToTextControllerAudioTranscriptionOrDefaultAsync(Option<System.IO.Stream> audio = default, Option<string> audioUrl = default, Option<string> languageBehaviour = default, Option<string> language = default, Option<string> transcriptionHint = default, Option<bool> toggleDiarization = default, Option<int> diarizationNumSpeakers = default, Option<int> diarizationMinSpeakers = default, Option<int> diarizationMaxSpeakers = default, Option<bool> toggleDirectTranslate = default, Option<string> targetTranslationLanguage = default, Option<string> outputFormat = default, Option<bool> toggleNoiseReduction = default, Option<bool> toggleAccurateWordsTimestamps = default, Option<string> webhookUrl = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="video"> (optional)</param>
        /// <param name="videoUrl"> (optional, default to &quot;http://files.gladia.io/example/audio-transcription/split_infinity.wav&quot;)</param>
        /// <param name="languageBehaviour"> (optional, default to automatic single language)</param>
        /// <param name="language"> (optional)</param>
        /// <param name="transcriptionHint"> (optional)</param>
        /// <param name="toggleDiarization"> (optional, default to false)</param>
        /// <param name="diarizationNumSpeakers"> (optional)</param>
        /// <param name="diarizationMinSpeakers"> (optional)</param>
        /// <param name="diarizationMaxSpeakers"> (optional)</param>
        /// <param name="toggleDirectTranslate"> (optional, default to false)</param>
        /// <param name="targetTranslationLanguage"> (optional)</param>
        /// <param name="outputFormat"> (optional, default to json)</param>
        /// <param name="toggleNoiseReduction"> (optional, default to false)</param>
        /// <param name="toggleAccurateWordsTimestamps"> (optional, default to false)</param>
        /// <param name="webhookUrl"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IVideoToTextControllerVideoTranscriptionApiResponse"/>&gt;</returns>
        Task<IVideoToTextControllerVideoTranscriptionApiResponse> VideoToTextControllerVideoTranscriptionAsync(Option<System.IO.Stream> video = default, Option<string> videoUrl = default, Option<string> languageBehaviour = default, Option<string> language = default, Option<string> transcriptionHint = default, Option<bool> toggleDiarization = default, Option<int> diarizationNumSpeakers = default, Option<int> diarizationMinSpeakers = default, Option<int> diarizationMaxSpeakers = default, Option<bool> toggleDirectTranslate = default, Option<string> targetTranslationLanguage = default, Option<string> outputFormat = default, Option<bool> toggleNoiseReduction = default, Option<bool> toggleAccurateWordsTimestamps = default, Option<string> webhookUrl = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <param name="video"> (optional)</param>
        /// <param name="videoUrl"> (optional, default to &quot;http://files.gladia.io/example/audio-transcription/split_infinity.wav&quot;)</param>
        /// <param name="languageBehaviour"> (optional, default to automatic single language)</param>
        /// <param name="language"> (optional)</param>
        /// <param name="transcriptionHint"> (optional)</param>
        /// <param name="toggleDiarization"> (optional, default to false)</param>
        /// <param name="diarizationNumSpeakers"> (optional)</param>
        /// <param name="diarizationMinSpeakers"> (optional)</param>
        /// <param name="diarizationMaxSpeakers"> (optional)</param>
        /// <param name="toggleDirectTranslate"> (optional, default to false)</param>
        /// <param name="targetTranslationLanguage"> (optional)</param>
        /// <param name="outputFormat"> (optional, default to json)</param>
        /// <param name="toggleNoiseReduction"> (optional, default to false)</param>
        /// <param name="toggleAccurateWordsTimestamps"> (optional, default to false)</param>
        /// <param name="webhookUrl"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IVideoToTextControllerVideoTranscriptionApiResponse"/>?&gt;</returns>
        Task<IVideoToTextControllerVideoTranscriptionApiResponse?> VideoToTextControllerVideoTranscriptionOrDefaultAsync(Option<System.IO.Stream> video = default, Option<string> videoUrl = default, Option<string> languageBehaviour = default, Option<string> language = default, Option<string> transcriptionHint = default, Option<bool> toggleDiarization = default, Option<int> diarizationNumSpeakers = default, Option<int> diarizationMinSpeakers = default, Option<int> diarizationMaxSpeakers = default, Option<bool> toggleDirectTranslate = default, Option<string> targetTranslationLanguage = default, Option<string> outputFormat = default, Option<bool> toggleNoiseReduction = default, Option<bool> toggleAccurateWordsTimestamps = default, Option<string> webhookUrl = default, System.Threading.CancellationToken cancellationToken = default);
    }

    /// <summary>
    /// The <see cref="IVideoToTextControllerVideoTranscriptionApiResponse"/>
    /// </summary>
    public interface IVideoToTextControllerVideoTranscriptionApiResponse : Gladia.SDK.Client.IApiResponse
    {
        /// <summary>
        /// Returns true if the response is 200 Ok
        /// </summary>
        /// <returns></returns>
        bool IsOk { get; }
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public class TranscriptionV1ApiEvents
    {
        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs>? OnAudioToTextControllerAudioTranscription;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs>? OnErrorAudioToTextControllerAudioTranscription;

        internal void ExecuteOnAudioToTextControllerAudioTranscription(AudioToTextApi.AudioToTextControllerAudioTranscriptionApiResponse apiResponse)
        {
            OnAudioToTextControllerAudioTranscription?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorAudioToTextControllerAudioTranscription(Exception exception)
        {
            OnErrorAudioToTextControllerAudioTranscription?.Invoke(this, new ExceptionEventArgs(exception));
        }

        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs>? OnVideoToTextControllerVideoTranscription;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs>? OnErrorVideoToTextControllerVideoTranscription;

        internal void ExecuteOnVideoToTextControllerVideoTranscription(TranscriptionV1Api.VideoToTextControllerVideoTranscriptionApiResponse apiResponse)
        {
            OnVideoToTextControllerVideoTranscription?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorVideoToTextControllerVideoTranscription(Exception exception)
        {
            OnErrorVideoToTextControllerVideoTranscription?.Invoke(this, new ExceptionEventArgs(exception));
        }
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public sealed partial class TranscriptionV1Api : ITranscriptionV1Api
    {
        private JsonSerializerOptions _jsonSerializerOptions;

        /// <summary>
        /// The logger factory
        /// </summary>
        public ILoggerFactory LoggerFactory { get; }

        /// <summary>
        /// The logger
        /// </summary>
        public ILogger<TranscriptionV1Api> Logger { get; }

        /// <summary>
        /// The HttpClient
        /// </summary>
        public HttpClient HttpClient { get; }

        /// <summary>
        /// The class containing the events
        /// </summary>
        public TranscriptionV1ApiEvents Events { get; }

        /// <summary>
        /// A token provider of type <see cref="ApiKeyProvider"/>
        /// </summary>
        public TokenProvider<ApiKeyToken> ApiKeyProvider { get; }

        /// <summary>
        /// Initializes a new instance of the <see cref="TranscriptionV1Api"/> class.
        /// </summary>
        /// <returns></returns>
        public TranscriptionV1Api(ILogger<TranscriptionV1Api> logger, ILoggerFactory loggerFactory, HttpClient httpClient, JsonSerializerOptionsProvider jsonSerializerOptionsProvider, TranscriptionV1ApiEvents transcriptionV1ApiEvents,
            TokenProvider<ApiKeyToken> apiKeyProvider)
        {
            _jsonSerializerOptions = jsonSerializerOptionsProvider.Options;
            LoggerFactory = loggerFactory;
            Logger = LoggerFactory.CreateLogger<TranscriptionV1Api>();
            HttpClient = httpClient;
            Events = transcriptionV1ApiEvents;
            ApiKeyProvider = apiKeyProvider;
        }

        partial void FormatAudioToTextControllerAudioTranscription(ref Option<System.IO.Stream> audio, ref Option<string> audioUrl, ref Option<string> languageBehaviour, ref Option<string> language, ref Option<string> transcriptionHint, ref Option<bool> toggleDiarization, ref Option<int> diarizationNumSpeakers, ref Option<int> diarizationMinSpeakers, ref Option<int> diarizationMaxSpeakers, ref Option<bool> toggleDirectTranslate, ref Option<string> targetTranslationLanguage, ref Option<string> outputFormat, ref Option<bool> toggleNoiseReduction, ref Option<bool> toggleAccurateWordsTimestamps, ref Option<string> webhookUrl);

        /// <summary>
        /// Validates the request parameters
        /// </summary>
        /// <param name="audio"></param>
        /// <param name="audioUrl"></param>
        /// <param name="languageBehaviour"></param>
        /// <param name="language"></param>
        /// <param name="transcriptionHint"></param>
        /// <param name="targetTranslationLanguage"></param>
        /// <param name="outputFormat"></param>
        /// <param name="webhookUrl"></param>
        /// <returns></returns>
        private void ValidateAudioToTextControllerAudioTranscription(Option<System.IO.Stream> audio, Option<string> audioUrl, Option<string> languageBehaviour, Option<string> language, Option<string> transcriptionHint, Option<string> targetTranslationLanguage, Option<string> outputFormat, Option<string> webhookUrl)
        {
            if (audio.IsSet && audio.Value == null)
                throw new ArgumentNullException(nameof(audio));

            if (audioUrl.IsSet && audioUrl.Value == null)
                throw new ArgumentNullException(nameof(audioUrl));

            if (languageBehaviour.IsSet && languageBehaviour.Value == null)
                throw new ArgumentNullException(nameof(languageBehaviour));

            if (language.IsSet && language.Value == null)
                throw new ArgumentNullException(nameof(language));

            if (transcriptionHint.IsSet && transcriptionHint.Value == null)
                throw new ArgumentNullException(nameof(transcriptionHint));

            if (targetTranslationLanguage.IsSet && targetTranslationLanguage.Value == null)
                throw new ArgumentNullException(nameof(targetTranslationLanguage));

            if (outputFormat.IsSet && outputFormat.Value == null)
                throw new ArgumentNullException(nameof(outputFormat));

            if (webhookUrl.IsSet && webhookUrl.Value == null)
                throw new ArgumentNullException(nameof(webhookUrl));
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="audio"></param>
        /// <param name="audioUrl"></param>
        /// <param name="languageBehaviour"></param>
        /// <param name="language"></param>
        /// <param name="transcriptionHint"></param>
        /// <param name="toggleDiarization"></param>
        /// <param name="diarizationNumSpeakers"></param>
        /// <param name="diarizationMinSpeakers"></param>
        /// <param name="diarizationMaxSpeakers"></param>
        /// <param name="toggleDirectTranslate"></param>
        /// <param name="targetTranslationLanguage"></param>
        /// <param name="outputFormat"></param>
        /// <param name="toggleNoiseReduction"></param>
        /// <param name="toggleAccurateWordsTimestamps"></param>
        /// <param name="webhookUrl"></param>
        private void AfterAudioToTextControllerAudioTranscriptionDefaultImplementation(IAudioToTextControllerAudioTranscriptionApiResponse apiResponseLocalVar, Option<System.IO.Stream> audio, Option<string> audioUrl, Option<string> languageBehaviour, Option<string> language, Option<string> transcriptionHint, Option<bool> toggleDiarization, Option<int> diarizationNumSpeakers, Option<int> diarizationMinSpeakers, Option<int> diarizationMaxSpeakers, Option<bool> toggleDirectTranslate, Option<string> targetTranslationLanguage, Option<string> outputFormat, Option<bool> toggleNoiseReduction, Option<bool> toggleAccurateWordsTimestamps, Option<string> webhookUrl)
        {
            bool suppressDefaultLog = false;
            AfterAudioToTextControllerAudioTranscription(ref suppressDefaultLog, apiResponseLocalVar, audio, audioUrl, languageBehaviour, language, transcriptionHint, toggleDiarization, diarizationNumSpeakers, diarizationMinSpeakers, diarizationMaxSpeakers, toggleDirectTranslate, targetTranslationLanguage, outputFormat, toggleNoiseReduction, toggleAccurateWordsTimestamps, webhookUrl);
            if (!suppressDefaultLog)
                Logger.LogInformation("{0,-9} | {1} | {3}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="audio"></param>
        /// <param name="audioUrl"></param>
        /// <param name="languageBehaviour"></param>
        /// <param name="language"></param>
        /// <param name="transcriptionHint"></param>
        /// <param name="toggleDiarization"></param>
        /// <param name="diarizationNumSpeakers"></param>
        /// <param name="diarizationMinSpeakers"></param>
        /// <param name="diarizationMaxSpeakers"></param>
        /// <param name="toggleDirectTranslate"></param>
        /// <param name="targetTranslationLanguage"></param>
        /// <param name="outputFormat"></param>
        /// <param name="toggleNoiseReduction"></param>
        /// <param name="toggleAccurateWordsTimestamps"></param>
        /// <param name="webhookUrl"></param>
        partial void AfterAudioToTextControllerAudioTranscription(ref bool suppressDefaultLog, IAudioToTextControllerAudioTranscriptionApiResponse apiResponseLocalVar, Option<System.IO.Stream> audio, Option<string> audioUrl, Option<string> languageBehaviour, Option<string> language, Option<string> transcriptionHint, Option<bool> toggleDiarization, Option<int> diarizationNumSpeakers, Option<int> diarizationMinSpeakers, Option<int> diarizationMaxSpeakers, Option<bool> toggleDirectTranslate, Option<string> targetTranslationLanguage, Option<string> outputFormat, Option<bool> toggleNoiseReduction, Option<bool> toggleAccurateWordsTimestamps, Option<string> webhookUrl);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="audio"></param>
        /// <param name="audioUrl"></param>
        /// <param name="languageBehaviour"></param>
        /// <param name="language"></param>
        /// <param name="transcriptionHint"></param>
        /// <param name="toggleDiarization"></param>
        /// <param name="diarizationNumSpeakers"></param>
        /// <param name="diarizationMinSpeakers"></param>
        /// <param name="diarizationMaxSpeakers"></param>
        /// <param name="toggleDirectTranslate"></param>
        /// <param name="targetTranslationLanguage"></param>
        /// <param name="outputFormat"></param>
        /// <param name="toggleNoiseReduction"></param>
        /// <param name="toggleAccurateWordsTimestamps"></param>
        /// <param name="webhookUrl"></param>
        private void OnErrorAudioToTextControllerAudioTranscriptionDefaultImplementation(Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, Option<System.IO.Stream> audio, Option<string> audioUrl, Option<string> languageBehaviour, Option<string> language, Option<string> transcriptionHint, Option<bool> toggleDiarization, Option<int> diarizationNumSpeakers, Option<int> diarizationMinSpeakers, Option<int> diarizationMaxSpeakers, Option<bool> toggleDirectTranslate, Option<string> targetTranslationLanguage, Option<string> outputFormat, Option<bool> toggleNoiseReduction, Option<bool> toggleAccurateWordsTimestamps, Option<string> webhookUrl)
        {
            bool suppressDefaultLogLocalVar = false;
            OnErrorAudioToTextControllerAudioTranscription(ref suppressDefaultLogLocalVar, exceptionLocalVar, pathFormatLocalVar, pathLocalVar, audio, audioUrl, languageBehaviour, language, transcriptionHint, toggleDiarization, diarizationNumSpeakers, diarizationMinSpeakers, diarizationMaxSpeakers, toggleDirectTranslate, targetTranslationLanguage, outputFormat, toggleNoiseReduction, toggleAccurateWordsTimestamps, webhookUrl);
            if (!suppressDefaultLogLocalVar)
                Logger.LogError(exceptionLocalVar, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLogLocalVar"></param>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="audio"></param>
        /// <param name="audioUrl"></param>
        /// <param name="languageBehaviour"></param>
        /// <param name="language"></param>
        /// <param name="transcriptionHint"></param>
        /// <param name="toggleDiarization"></param>
        /// <param name="diarizationNumSpeakers"></param>
        /// <param name="diarizationMinSpeakers"></param>
        /// <param name="diarizationMaxSpeakers"></param>
        /// <param name="toggleDirectTranslate"></param>
        /// <param name="targetTranslationLanguage"></param>
        /// <param name="outputFormat"></param>
        /// <param name="toggleNoiseReduction"></param>
        /// <param name="toggleAccurateWordsTimestamps"></param>
        /// <param name="webhookUrl"></param>
        partial void OnErrorAudioToTextControllerAudioTranscription(ref bool suppressDefaultLogLocalVar, Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, Option<System.IO.Stream> audio, Option<string> audioUrl, Option<string> languageBehaviour, Option<string> language, Option<string> transcriptionHint, Option<bool> toggleDiarization, Option<int> diarizationNumSpeakers, Option<int> diarizationMinSpeakers, Option<int> diarizationMaxSpeakers, Option<bool> toggleDirectTranslate, Option<string> targetTranslationLanguage, Option<string> outputFormat, Option<bool> toggleNoiseReduction, Option<bool> toggleAccurateWordsTimestamps, Option<string> webhookUrl);

        /// <summary>
        ///  
        /// </summary>
        /// <param name="audio"> (optional)</param>
        /// <param name="audioUrl"> (optional, default to &quot;http://files.gladia.io/example/audio-transcription/split_infinity.wav&quot;)</param>
        /// <param name="languageBehaviour"> (optional, default to automatic single language)</param>
        /// <param name="language"> (optional)</param>
        /// <param name="transcriptionHint"> (optional)</param>
        /// <param name="toggleDiarization"> (optional, default to false)</param>
        /// <param name="diarizationNumSpeakers"> (optional)</param>
        /// <param name="diarizationMinSpeakers"> (optional)</param>
        /// <param name="diarizationMaxSpeakers"> (optional)</param>
        /// <param name="toggleDirectTranslate"> (optional, default to false)</param>
        /// <param name="targetTranslationLanguage"> (optional)</param>
        /// <param name="outputFormat"> (optional, default to json)</param>
        /// <param name="toggleNoiseReduction"> (optional, default to false)</param>
        /// <param name="toggleAccurateWordsTimestamps"> (optional, default to false)</param>
        /// <param name="webhookUrl"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IAudioToTextControllerAudioTranscriptionApiResponse"/>&gt;</returns>
        public async Task<IAudioToTextControllerAudioTranscriptionApiResponse?> AudioToTextControllerAudioTranscriptionOrDefaultAsync(Option<System.IO.Stream> audio = default, Option<string> audioUrl = default, Option<string> languageBehaviour = default, Option<string> language = default, Option<string> transcriptionHint = default, Option<bool> toggleDiarization = default, Option<int> diarizationNumSpeakers = default, Option<int> diarizationMinSpeakers = default, Option<int> diarizationMaxSpeakers = default, Option<bool> toggleDirectTranslate = default, Option<string> targetTranslationLanguage = default, Option<string> outputFormat = default, Option<bool> toggleNoiseReduction = default, Option<bool> toggleAccurateWordsTimestamps = default, Option<string> webhookUrl = default, System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await AudioToTextControllerAudioTranscriptionAsync(audio, audioUrl, languageBehaviour, language, transcriptionHint, toggleDiarization, diarizationNumSpeakers, diarizationMinSpeakers, diarizationMaxSpeakers, toggleDirectTranslate, targetTranslationLanguage, outputFormat, toggleNoiseReduction, toggleAccurateWordsTimestamps, webhookUrl, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="audio"> (optional)</param>
        /// <param name="audioUrl"> (optional, default to &quot;http://files.gladia.io/example/audio-transcription/split_infinity.wav&quot;)</param>
        /// <param name="languageBehaviour"> (optional, default to automatic single language)</param>
        /// <param name="language"> (optional)</param>
        /// <param name="transcriptionHint"> (optional)</param>
        /// <param name="toggleDiarization"> (optional, default to false)</param>
        /// <param name="diarizationNumSpeakers"> (optional)</param>
        /// <param name="diarizationMinSpeakers"> (optional)</param>
        /// <param name="diarizationMaxSpeakers"> (optional)</param>
        /// <param name="toggleDirectTranslate"> (optional, default to false)</param>
        /// <param name="targetTranslationLanguage"> (optional)</param>
        /// <param name="outputFormat"> (optional, default to json)</param>
        /// <param name="toggleNoiseReduction"> (optional, default to false)</param>
        /// <param name="toggleAccurateWordsTimestamps"> (optional, default to false)</param>
        /// <param name="webhookUrl"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IAudioToTextControllerAudioTranscriptionApiResponse"/>&gt;</returns>
        public async Task<IAudioToTextControllerAudioTranscriptionApiResponse> AudioToTextControllerAudioTranscriptionAsync(Option<System.IO.Stream> audio = default, Option<string> audioUrl = default, Option<string> languageBehaviour = default, Option<string> language = default, Option<string> transcriptionHint = default, Option<bool> toggleDiarization = default, Option<int> diarizationNumSpeakers = default, Option<int> diarizationMinSpeakers = default, Option<int> diarizationMaxSpeakers = default, Option<bool> toggleDirectTranslate = default, Option<string> targetTranslationLanguage = default, Option<string> outputFormat = default, Option<bool> toggleNoiseReduction = default, Option<bool> toggleAccurateWordsTimestamps = default, Option<string> webhookUrl = default, System.Threading.CancellationToken cancellationToken = default)
        {
            UriBuilder uriBuilderLocalVar = new UriBuilder();

            try
            {
                ValidateAudioToTextControllerAudioTranscription(audio, audioUrl, languageBehaviour, language, transcriptionHint, targetTranslationLanguage, outputFormat, webhookUrl);

                FormatAudioToTextControllerAudioTranscription(ref audio, ref audioUrl, ref languageBehaviour, ref language, ref transcriptionHint, ref toggleDiarization, ref diarizationNumSpeakers, ref diarizationMinSpeakers, ref diarizationMaxSpeakers, ref toggleDirectTranslate, ref targetTranslationLanguage, ref outputFormat, ref toggleNoiseReduction, ref toggleAccurateWordsTimestamps, ref webhookUrl);

                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    uriBuilderLocalVar.Host = HttpClient.BaseAddress!.Host;
                    uriBuilderLocalVar.Port = HttpClient.BaseAddress.Port;
                    uriBuilderLocalVar.Scheme = HttpClient.BaseAddress.Scheme;
                    uriBuilderLocalVar.Path = HttpClient.BaseAddress.AbsolutePath == "/"
                        ? "/audio/text/audio-transcription"
                        : string.Concat(HttpClient.BaseAddress.AbsolutePath, "/audio/text/audio-transcription");

                    MultipartContent multipartContentLocalVar = new MultipartContent();

                    httpRequestMessageLocalVar.Content = multipartContentLocalVar;

                    List<KeyValuePair<string?, string?>> formParameterLocalVars = new List<KeyValuePair<string?, string?>>();

                    multipartContentLocalVar.Add(new FormUrlEncodedContent(formParameterLocalVars));                    if (audio.IsSet)
                        multipartContentLocalVar.Add(new StreamContent(audio.Value));

                    if (audioUrl.IsSet)
                        formParameterLocalVars.Add(new KeyValuePair<string?, string?>("audio_url", ClientUtils.ParameterToString(audioUrl.Value)));

                    if (languageBehaviour.IsSet)
                        formParameterLocalVars.Add(new KeyValuePair<string?, string?>("language_behaviour", ClientUtils.ParameterToString(languageBehaviour.Value)));

                    if (language.IsSet)
                        formParameterLocalVars.Add(new KeyValuePair<string?, string?>("language", ClientUtils.ParameterToString(language.Value)));

                    if (transcriptionHint.IsSet)
                        formParameterLocalVars.Add(new KeyValuePair<string?, string?>("transcription_hint", ClientUtils.ParameterToString(transcriptionHint.Value)));

                    if (toggleDiarization.IsSet)
                        formParameterLocalVars.Add(new KeyValuePair<string?, string?>("toggle_diarization", ClientUtils.ParameterToString(toggleDiarization.Value)));

                    if (diarizationNumSpeakers.IsSet)
                        formParameterLocalVars.Add(new KeyValuePair<string?, string?>("diarization_num_speakers", ClientUtils.ParameterToString(diarizationNumSpeakers.Value)));

                    if (diarizationMinSpeakers.IsSet)
                        formParameterLocalVars.Add(new KeyValuePair<string?, string?>("diarization_min_speakers", ClientUtils.ParameterToString(diarizationMinSpeakers.Value)));

                    if (diarizationMaxSpeakers.IsSet)
                        formParameterLocalVars.Add(new KeyValuePair<string?, string?>("diarization_max_speakers", ClientUtils.ParameterToString(diarizationMaxSpeakers.Value)));

                    if (toggleDirectTranslate.IsSet)
                        formParameterLocalVars.Add(new KeyValuePair<string?, string?>("toggle_direct_translate", ClientUtils.ParameterToString(toggleDirectTranslate.Value)));

                    if (targetTranslationLanguage.IsSet)
                        formParameterLocalVars.Add(new KeyValuePair<string?, string?>("target_translation_language", ClientUtils.ParameterToString(targetTranslationLanguage.Value)));

                    if (outputFormat.IsSet)
                        formParameterLocalVars.Add(new KeyValuePair<string?, string?>("output_format", ClientUtils.ParameterToString(outputFormat.Value)));

                    if (toggleNoiseReduction.IsSet)
                        formParameterLocalVars.Add(new KeyValuePair<string?, string?>("toggle_noise_reduction", ClientUtils.ParameterToString(toggleNoiseReduction.Value)));

                    if (toggleAccurateWordsTimestamps.IsSet)
                        formParameterLocalVars.Add(new KeyValuePair<string?, string?>("toggle_accurate_words_timestamps", ClientUtils.ParameterToString(toggleAccurateWordsTimestamps.Value)));

                    if (webhookUrl.IsSet)
                        formParameterLocalVars.Add(new KeyValuePair<string?, string?>("webhook_url", ClientUtils.ParameterToString(webhookUrl.Value)));

                    List<TokenBase> tokenBaseLocalVars = new List<TokenBase>();
                    ApiKeyToken apiKeyTokenLocalVar1 = (ApiKeyToken) await ApiKeyProvider.GetAsync("x-gladia-key", cancellationToken).ConfigureAwait(false);
                    tokenBaseLocalVars.Add(apiKeyTokenLocalVar1);
                    apiKeyTokenLocalVar1.UseInHeader(httpRequestMessageLocalVar);

                    httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;

                    string[] contentTypes = new string[] {
                        "multipart/form-data"
                    };

                    string? contentTypeLocalVar = ClientUtils.SelectHeaderContentType(contentTypes);

                    if (contentTypeLocalVar != null && httpRequestMessageLocalVar.Content != null)
                        httpRequestMessageLocalVar.Content.Headers.ContentType = new MediaTypeHeaderValue(contentTypeLocalVar);

                    httpRequestMessageLocalVar.Method = HttpMethod.Post;

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await HttpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        ILogger<AudioToTextApi.AudioToTextControllerAudioTranscriptionApiResponse> apiResponseLoggerLocalVar = LoggerFactory.CreateLogger<AudioToTextApi.AudioToTextControllerAudioTranscriptionApiResponse>();
                        AudioToTextApi.AudioToTextControllerAudioTranscriptionApiResponse apiResponseLocalVar;

                        switch ((int)httpResponseMessageLocalVar.StatusCode) {
                            default: {
                                string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
                                apiResponseLocalVar = new(apiResponseLoggerLocalVar, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/audio/text/audio-transcription", requestedAtLocalVar, _jsonSerializerOptions);

                                break;
                            }
                        }

                        AfterAudioToTextControllerAudioTranscriptionDefaultImplementation(apiResponseLocalVar, audio, audioUrl, languageBehaviour, language, transcriptionHint, toggleDiarization, diarizationNumSpeakers, diarizationMinSpeakers, diarizationMaxSpeakers, toggleDirectTranslate, targetTranslationLanguage, outputFormat, toggleNoiseReduction, toggleAccurateWordsTimestamps, webhookUrl);

                        Events.ExecuteOnAudioToTextControllerAudioTranscription(apiResponseLocalVar);

                        if (apiResponseLocalVar.StatusCode == (HttpStatusCode) 429)
                            foreach(TokenBase tokenBaseLocalVar in tokenBaseLocalVars)
                                tokenBaseLocalVar.BeginRateLimit();

                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorAudioToTextControllerAudioTranscriptionDefaultImplementation(e, "/audio/text/audio-transcription", uriBuilderLocalVar.Path, audio, audioUrl, languageBehaviour, language, transcriptionHint, toggleDiarization, diarizationNumSpeakers, diarizationMinSpeakers, diarizationMaxSpeakers, toggleDirectTranslate, targetTranslationLanguage, outputFormat, toggleNoiseReduction, toggleAccurateWordsTimestamps, webhookUrl);
                Events.ExecuteOnErrorAudioToTextControllerAudioTranscription(e);
                throw;
            }
        }

        partial void FormatVideoToTextControllerVideoTranscription(ref Option<System.IO.Stream> video, ref Option<string> videoUrl, ref Option<string> languageBehaviour, ref Option<string> language, ref Option<string> transcriptionHint, ref Option<bool> toggleDiarization, ref Option<int> diarizationNumSpeakers, ref Option<int> diarizationMinSpeakers, ref Option<int> diarizationMaxSpeakers, ref Option<bool> toggleDirectTranslate, ref Option<string> targetTranslationLanguage, ref Option<string> outputFormat, ref Option<bool> toggleNoiseReduction, ref Option<bool> toggleAccurateWordsTimestamps, ref Option<string> webhookUrl);

        /// <summary>
        /// Validates the request parameters
        /// </summary>
        /// <param name="video"></param>
        /// <param name="videoUrl"></param>
        /// <param name="languageBehaviour"></param>
        /// <param name="language"></param>
        /// <param name="transcriptionHint"></param>
        /// <param name="targetTranslationLanguage"></param>
        /// <param name="outputFormat"></param>
        /// <param name="webhookUrl"></param>
        /// <returns></returns>
        private void ValidateVideoToTextControllerVideoTranscription(Option<System.IO.Stream> video, Option<string> videoUrl, Option<string> languageBehaviour, Option<string> language, Option<string> transcriptionHint, Option<string> targetTranslationLanguage, Option<string> outputFormat, Option<string> webhookUrl)
        {
            if (video.IsSet && video.Value == null)
                throw new ArgumentNullException(nameof(video));

            if (videoUrl.IsSet && videoUrl.Value == null)
                throw new ArgumentNullException(nameof(videoUrl));

            if (languageBehaviour.IsSet && languageBehaviour.Value == null)
                throw new ArgumentNullException(nameof(languageBehaviour));

            if (language.IsSet && language.Value == null)
                throw new ArgumentNullException(nameof(language));

            if (transcriptionHint.IsSet && transcriptionHint.Value == null)
                throw new ArgumentNullException(nameof(transcriptionHint));

            if (targetTranslationLanguage.IsSet && targetTranslationLanguage.Value == null)
                throw new ArgumentNullException(nameof(targetTranslationLanguage));

            if (outputFormat.IsSet && outputFormat.Value == null)
                throw new ArgumentNullException(nameof(outputFormat));

            if (webhookUrl.IsSet && webhookUrl.Value == null)
                throw new ArgumentNullException(nameof(webhookUrl));
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="video"></param>
        /// <param name="videoUrl"></param>
        /// <param name="languageBehaviour"></param>
        /// <param name="language"></param>
        /// <param name="transcriptionHint"></param>
        /// <param name="toggleDiarization"></param>
        /// <param name="diarizationNumSpeakers"></param>
        /// <param name="diarizationMinSpeakers"></param>
        /// <param name="diarizationMaxSpeakers"></param>
        /// <param name="toggleDirectTranslate"></param>
        /// <param name="targetTranslationLanguage"></param>
        /// <param name="outputFormat"></param>
        /// <param name="toggleNoiseReduction"></param>
        /// <param name="toggleAccurateWordsTimestamps"></param>
        /// <param name="webhookUrl"></param>
        private void AfterVideoToTextControllerVideoTranscriptionDefaultImplementation(IVideoToTextControllerVideoTranscriptionApiResponse apiResponseLocalVar, Option<System.IO.Stream> video, Option<string> videoUrl, Option<string> languageBehaviour, Option<string> language, Option<string> transcriptionHint, Option<bool> toggleDiarization, Option<int> diarizationNumSpeakers, Option<int> diarizationMinSpeakers, Option<int> diarizationMaxSpeakers, Option<bool> toggleDirectTranslate, Option<string> targetTranslationLanguage, Option<string> outputFormat, Option<bool> toggleNoiseReduction, Option<bool> toggleAccurateWordsTimestamps, Option<string> webhookUrl)
        {
            bool suppressDefaultLog = false;
            AfterVideoToTextControllerVideoTranscription(ref suppressDefaultLog, apiResponseLocalVar, video, videoUrl, languageBehaviour, language, transcriptionHint, toggleDiarization, diarizationNumSpeakers, diarizationMinSpeakers, diarizationMaxSpeakers, toggleDirectTranslate, targetTranslationLanguage, outputFormat, toggleNoiseReduction, toggleAccurateWordsTimestamps, webhookUrl);
            if (!suppressDefaultLog)
                Logger.LogInformation("{0,-9} | {1} | {3}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="video"></param>
        /// <param name="videoUrl"></param>
        /// <param name="languageBehaviour"></param>
        /// <param name="language"></param>
        /// <param name="transcriptionHint"></param>
        /// <param name="toggleDiarization"></param>
        /// <param name="diarizationNumSpeakers"></param>
        /// <param name="diarizationMinSpeakers"></param>
        /// <param name="diarizationMaxSpeakers"></param>
        /// <param name="toggleDirectTranslate"></param>
        /// <param name="targetTranslationLanguage"></param>
        /// <param name="outputFormat"></param>
        /// <param name="toggleNoiseReduction"></param>
        /// <param name="toggleAccurateWordsTimestamps"></param>
        /// <param name="webhookUrl"></param>
        partial void AfterVideoToTextControllerVideoTranscription(ref bool suppressDefaultLog, IVideoToTextControllerVideoTranscriptionApiResponse apiResponseLocalVar, Option<System.IO.Stream> video, Option<string> videoUrl, Option<string> languageBehaviour, Option<string> language, Option<string> transcriptionHint, Option<bool> toggleDiarization, Option<int> diarizationNumSpeakers, Option<int> diarizationMinSpeakers, Option<int> diarizationMaxSpeakers, Option<bool> toggleDirectTranslate, Option<string> targetTranslationLanguage, Option<string> outputFormat, Option<bool> toggleNoiseReduction, Option<bool> toggleAccurateWordsTimestamps, Option<string> webhookUrl);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="video"></param>
        /// <param name="videoUrl"></param>
        /// <param name="languageBehaviour"></param>
        /// <param name="language"></param>
        /// <param name="transcriptionHint"></param>
        /// <param name="toggleDiarization"></param>
        /// <param name="diarizationNumSpeakers"></param>
        /// <param name="diarizationMinSpeakers"></param>
        /// <param name="diarizationMaxSpeakers"></param>
        /// <param name="toggleDirectTranslate"></param>
        /// <param name="targetTranslationLanguage"></param>
        /// <param name="outputFormat"></param>
        /// <param name="toggleNoiseReduction"></param>
        /// <param name="toggleAccurateWordsTimestamps"></param>
        /// <param name="webhookUrl"></param>
        private void OnErrorVideoToTextControllerVideoTranscriptionDefaultImplementation(Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, Option<System.IO.Stream> video, Option<string> videoUrl, Option<string> languageBehaviour, Option<string> language, Option<string> transcriptionHint, Option<bool> toggleDiarization, Option<int> diarizationNumSpeakers, Option<int> diarizationMinSpeakers, Option<int> diarizationMaxSpeakers, Option<bool> toggleDirectTranslate, Option<string> targetTranslationLanguage, Option<string> outputFormat, Option<bool> toggleNoiseReduction, Option<bool> toggleAccurateWordsTimestamps, Option<string> webhookUrl)
        {
            bool suppressDefaultLogLocalVar = false;
            OnErrorVideoToTextControllerVideoTranscription(ref suppressDefaultLogLocalVar, exceptionLocalVar, pathFormatLocalVar, pathLocalVar, video, videoUrl, languageBehaviour, language, transcriptionHint, toggleDiarization, diarizationNumSpeakers, diarizationMinSpeakers, diarizationMaxSpeakers, toggleDirectTranslate, targetTranslationLanguage, outputFormat, toggleNoiseReduction, toggleAccurateWordsTimestamps, webhookUrl);
            if (!suppressDefaultLogLocalVar)
                Logger.LogError(exceptionLocalVar, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLogLocalVar"></param>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="video"></param>
        /// <param name="videoUrl"></param>
        /// <param name="languageBehaviour"></param>
        /// <param name="language"></param>
        /// <param name="transcriptionHint"></param>
        /// <param name="toggleDiarization"></param>
        /// <param name="diarizationNumSpeakers"></param>
        /// <param name="diarizationMinSpeakers"></param>
        /// <param name="diarizationMaxSpeakers"></param>
        /// <param name="toggleDirectTranslate"></param>
        /// <param name="targetTranslationLanguage"></param>
        /// <param name="outputFormat"></param>
        /// <param name="toggleNoiseReduction"></param>
        /// <param name="toggleAccurateWordsTimestamps"></param>
        /// <param name="webhookUrl"></param>
        partial void OnErrorVideoToTextControllerVideoTranscription(ref bool suppressDefaultLogLocalVar, Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, Option<System.IO.Stream> video, Option<string> videoUrl, Option<string> languageBehaviour, Option<string> language, Option<string> transcriptionHint, Option<bool> toggleDiarization, Option<int> diarizationNumSpeakers, Option<int> diarizationMinSpeakers, Option<int> diarizationMaxSpeakers, Option<bool> toggleDirectTranslate, Option<string> targetTranslationLanguage, Option<string> outputFormat, Option<bool> toggleNoiseReduction, Option<bool> toggleAccurateWordsTimestamps, Option<string> webhookUrl);

        /// <summary>
        ///  
        /// </summary>
        /// <param name="video"> (optional)</param>
        /// <param name="videoUrl"> (optional, default to &quot;http://files.gladia.io/example/audio-transcription/split_infinity.wav&quot;)</param>
        /// <param name="languageBehaviour"> (optional, default to automatic single language)</param>
        /// <param name="language"> (optional)</param>
        /// <param name="transcriptionHint"> (optional)</param>
        /// <param name="toggleDiarization"> (optional, default to false)</param>
        /// <param name="diarizationNumSpeakers"> (optional)</param>
        /// <param name="diarizationMinSpeakers"> (optional)</param>
        /// <param name="diarizationMaxSpeakers"> (optional)</param>
        /// <param name="toggleDirectTranslate"> (optional, default to false)</param>
        /// <param name="targetTranslationLanguage"> (optional)</param>
        /// <param name="outputFormat"> (optional, default to json)</param>
        /// <param name="toggleNoiseReduction"> (optional, default to false)</param>
        /// <param name="toggleAccurateWordsTimestamps"> (optional, default to false)</param>
        /// <param name="webhookUrl"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IVideoToTextControllerVideoTranscriptionApiResponse"/>&gt;</returns>
        public async Task<IVideoToTextControllerVideoTranscriptionApiResponse?> VideoToTextControllerVideoTranscriptionOrDefaultAsync(Option<System.IO.Stream> video = default, Option<string> videoUrl = default, Option<string> languageBehaviour = default, Option<string> language = default, Option<string> transcriptionHint = default, Option<bool> toggleDiarization = default, Option<int> diarizationNumSpeakers = default, Option<int> diarizationMinSpeakers = default, Option<int> diarizationMaxSpeakers = default, Option<bool> toggleDirectTranslate = default, Option<string> targetTranslationLanguage = default, Option<string> outputFormat = default, Option<bool> toggleNoiseReduction = default, Option<bool> toggleAccurateWordsTimestamps = default, Option<string> webhookUrl = default, System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await VideoToTextControllerVideoTranscriptionAsync(video, videoUrl, languageBehaviour, language, transcriptionHint, toggleDiarization, diarizationNumSpeakers, diarizationMinSpeakers, diarizationMaxSpeakers, toggleDirectTranslate, targetTranslationLanguage, outputFormat, toggleNoiseReduction, toggleAccurateWordsTimestamps, webhookUrl, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="video"> (optional)</param>
        /// <param name="videoUrl"> (optional, default to &quot;http://files.gladia.io/example/audio-transcription/split_infinity.wav&quot;)</param>
        /// <param name="languageBehaviour"> (optional, default to automatic single language)</param>
        /// <param name="language"> (optional)</param>
        /// <param name="transcriptionHint"> (optional)</param>
        /// <param name="toggleDiarization"> (optional, default to false)</param>
        /// <param name="diarizationNumSpeakers"> (optional)</param>
        /// <param name="diarizationMinSpeakers"> (optional)</param>
        /// <param name="diarizationMaxSpeakers"> (optional)</param>
        /// <param name="toggleDirectTranslate"> (optional, default to false)</param>
        /// <param name="targetTranslationLanguage"> (optional)</param>
        /// <param name="outputFormat"> (optional, default to json)</param>
        /// <param name="toggleNoiseReduction"> (optional, default to false)</param>
        /// <param name="toggleAccurateWordsTimestamps"> (optional, default to false)</param>
        /// <param name="webhookUrl"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IVideoToTextControllerVideoTranscriptionApiResponse"/>&gt;</returns>
        public async Task<IVideoToTextControllerVideoTranscriptionApiResponse> VideoToTextControllerVideoTranscriptionAsync(Option<System.IO.Stream> video = default, Option<string> videoUrl = default, Option<string> languageBehaviour = default, Option<string> language = default, Option<string> transcriptionHint = default, Option<bool> toggleDiarization = default, Option<int> diarizationNumSpeakers = default, Option<int> diarizationMinSpeakers = default, Option<int> diarizationMaxSpeakers = default, Option<bool> toggleDirectTranslate = default, Option<string> targetTranslationLanguage = default, Option<string> outputFormat = default, Option<bool> toggleNoiseReduction = default, Option<bool> toggleAccurateWordsTimestamps = default, Option<string> webhookUrl = default, System.Threading.CancellationToken cancellationToken = default)
        {
            UriBuilder uriBuilderLocalVar = new UriBuilder();

            try
            {
                ValidateVideoToTextControllerVideoTranscription(video, videoUrl, languageBehaviour, language, transcriptionHint, targetTranslationLanguage, outputFormat, webhookUrl);

                FormatVideoToTextControllerVideoTranscription(ref video, ref videoUrl, ref languageBehaviour, ref language, ref transcriptionHint, ref toggleDiarization, ref diarizationNumSpeakers, ref diarizationMinSpeakers, ref diarizationMaxSpeakers, ref toggleDirectTranslate, ref targetTranslationLanguage, ref outputFormat, ref toggleNoiseReduction, ref toggleAccurateWordsTimestamps, ref webhookUrl);

                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    uriBuilderLocalVar.Host = HttpClient.BaseAddress!.Host;
                    uriBuilderLocalVar.Port = HttpClient.BaseAddress.Port;
                    uriBuilderLocalVar.Scheme = HttpClient.BaseAddress.Scheme;
                    uriBuilderLocalVar.Path = HttpClient.BaseAddress.AbsolutePath == "/"
                        ? "/video/text/video-transcription"
                        : string.Concat(HttpClient.BaseAddress.AbsolutePath, "/video/text/video-transcription");

                    MultipartContent multipartContentLocalVar = new MultipartContent();

                    httpRequestMessageLocalVar.Content = multipartContentLocalVar;

                    List<KeyValuePair<string?, string?>> formParameterLocalVars = new List<KeyValuePair<string?, string?>>();

                    multipartContentLocalVar.Add(new FormUrlEncodedContent(formParameterLocalVars));                    if (video.IsSet)
                        multipartContentLocalVar.Add(new StreamContent(video.Value));

                    if (videoUrl.IsSet)
                        formParameterLocalVars.Add(new KeyValuePair<string?, string?>("video_url", ClientUtils.ParameterToString(videoUrl.Value)));

                    if (languageBehaviour.IsSet)
                        formParameterLocalVars.Add(new KeyValuePair<string?, string?>("language_behaviour", ClientUtils.ParameterToString(languageBehaviour.Value)));

                    if (language.IsSet)
                        formParameterLocalVars.Add(new KeyValuePair<string?, string?>("language", ClientUtils.ParameterToString(language.Value)));

                    if (transcriptionHint.IsSet)
                        formParameterLocalVars.Add(new KeyValuePair<string?, string?>("transcription_hint", ClientUtils.ParameterToString(transcriptionHint.Value)));

                    if (toggleDiarization.IsSet)
                        formParameterLocalVars.Add(new KeyValuePair<string?, string?>("toggle_diarization", ClientUtils.ParameterToString(toggleDiarization.Value)));

                    if (diarizationNumSpeakers.IsSet)
                        formParameterLocalVars.Add(new KeyValuePair<string?, string?>("diarization_num_speakers", ClientUtils.ParameterToString(diarizationNumSpeakers.Value)));

                    if (diarizationMinSpeakers.IsSet)
                        formParameterLocalVars.Add(new KeyValuePair<string?, string?>("diarization_min_speakers", ClientUtils.ParameterToString(diarizationMinSpeakers.Value)));

                    if (diarizationMaxSpeakers.IsSet)
                        formParameterLocalVars.Add(new KeyValuePair<string?, string?>("diarization_max_speakers", ClientUtils.ParameterToString(diarizationMaxSpeakers.Value)));

                    if (toggleDirectTranslate.IsSet)
                        formParameterLocalVars.Add(new KeyValuePair<string?, string?>("toggle_direct_translate", ClientUtils.ParameterToString(toggleDirectTranslate.Value)));

                    if (targetTranslationLanguage.IsSet)
                        formParameterLocalVars.Add(new KeyValuePair<string?, string?>("target_translation_language", ClientUtils.ParameterToString(targetTranslationLanguage.Value)));

                    if (outputFormat.IsSet)
                        formParameterLocalVars.Add(new KeyValuePair<string?, string?>("output_format", ClientUtils.ParameterToString(outputFormat.Value)));

                    if (toggleNoiseReduction.IsSet)
                        formParameterLocalVars.Add(new KeyValuePair<string?, string?>("toggle_noise_reduction", ClientUtils.ParameterToString(toggleNoiseReduction.Value)));

                    if (toggleAccurateWordsTimestamps.IsSet)
                        formParameterLocalVars.Add(new KeyValuePair<string?, string?>("toggle_accurate_words_timestamps", ClientUtils.ParameterToString(toggleAccurateWordsTimestamps.Value)));

                    if (webhookUrl.IsSet)
                        formParameterLocalVars.Add(new KeyValuePair<string?, string?>("webhook_url", ClientUtils.ParameterToString(webhookUrl.Value)));

                    List<TokenBase> tokenBaseLocalVars = new List<TokenBase>();
                    ApiKeyToken apiKeyTokenLocalVar1 = (ApiKeyToken) await ApiKeyProvider.GetAsync("x-gladia-key", cancellationToken).ConfigureAwait(false);
                    tokenBaseLocalVars.Add(apiKeyTokenLocalVar1);
                    apiKeyTokenLocalVar1.UseInHeader(httpRequestMessageLocalVar);

                    httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;

                    string[] contentTypes = new string[] {
                        "multipart/form-data"
                    };

                    string? contentTypeLocalVar = ClientUtils.SelectHeaderContentType(contentTypes);

                    if (contentTypeLocalVar != null && httpRequestMessageLocalVar.Content != null)
                        httpRequestMessageLocalVar.Content.Headers.ContentType = new MediaTypeHeaderValue(contentTypeLocalVar);

                    httpRequestMessageLocalVar.Method = HttpMethod.Post;

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await HttpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        ILogger<VideoToTextControllerVideoTranscriptionApiResponse> apiResponseLoggerLocalVar = LoggerFactory.CreateLogger<VideoToTextControllerVideoTranscriptionApiResponse>();
                        VideoToTextControllerVideoTranscriptionApiResponse apiResponseLocalVar;

                        switch ((int)httpResponseMessageLocalVar.StatusCode) {
                            default: {
                                string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
                                apiResponseLocalVar = new(apiResponseLoggerLocalVar, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/video/text/video-transcription", requestedAtLocalVar, _jsonSerializerOptions);

                                break;
                            }
                        }

                        AfterVideoToTextControllerVideoTranscriptionDefaultImplementation(apiResponseLocalVar, video, videoUrl, languageBehaviour, language, transcriptionHint, toggleDiarization, diarizationNumSpeakers, diarizationMinSpeakers, diarizationMaxSpeakers, toggleDirectTranslate, targetTranslationLanguage, outputFormat, toggleNoiseReduction, toggleAccurateWordsTimestamps, webhookUrl);

                        Events.ExecuteOnVideoToTextControllerVideoTranscription(apiResponseLocalVar);

                        if (apiResponseLocalVar.StatusCode == (HttpStatusCode) 429)
                            foreach(TokenBase tokenBaseLocalVar in tokenBaseLocalVars)
                                tokenBaseLocalVar.BeginRateLimit();

                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorVideoToTextControllerVideoTranscriptionDefaultImplementation(e, "/video/text/video-transcription", uriBuilderLocalVar.Path, video, videoUrl, languageBehaviour, language, transcriptionHint, toggleDiarization, diarizationNumSpeakers, diarizationMinSpeakers, diarizationMaxSpeakers, toggleDirectTranslate, targetTranslationLanguage, outputFormat, toggleNoiseReduction, toggleAccurateWordsTimestamps, webhookUrl);
                Events.ExecuteOnErrorVideoToTextControllerVideoTranscription(e);
                throw;
            }
        }

        /// <summary>
        /// The <see cref="VideoToTextControllerVideoTranscriptionApiResponse"/>
        /// </summary>
        public partial class VideoToTextControllerVideoTranscriptionApiResponse : Gladia.SDK.Client.ApiResponse, IVideoToTextControllerVideoTranscriptionApiResponse
        {
            /// <summary>
            /// The logger
            /// </summary>
            public ILogger<VideoToTextControllerVideoTranscriptionApiResponse> Logger { get; }

            /// <summary>
            /// The <see cref="VideoToTextControllerVideoTranscriptionApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="rawContent"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public VideoToTextControllerVideoTranscriptionApiResponse(ILogger<VideoToTextControllerVideoTranscriptionApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, string rawContent, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, rawContent, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            /// <summary>
            /// The <see cref="VideoToTextControllerVideoTranscriptionApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="contentStream"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public VideoToTextControllerVideoTranscriptionApiResponse(ILogger<VideoToTextControllerVideoTranscriptionApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, System.IO.Stream contentStream, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, contentStream, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            partial void OnCreated(global::System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage);

            /// <summary>
            /// Returns true if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public bool IsOk => 200 == (int)StatusCode;

            private void OnDeserializationErrorDefaultImplementation(Exception exception, HttpStatusCode httpStatusCode)
            {
                bool suppressDefaultLog = false;
                OnDeserializationError(ref suppressDefaultLog, exception, httpStatusCode);
                if (!suppressDefaultLog)
                    Logger.LogError(exception, "An error occurred while deserializing the {code} response.", httpStatusCode);
            }

            partial void OnDeserializationError(ref bool suppressDefaultLog, Exception exception, HttpStatusCode httpStatusCode);
        }
    }
}
