/*
 * Gladia Control API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Gladia.SDK.Model;
using Gladia.SDK.Client;
using System.Reflection;

namespace Gladia.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing AudioUploadMetadataDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AudioUploadMetadataDTOTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AudioUploadMetadataDTO
        //private AudioUploadMetadataDTO instance;

        public AudioUploadMetadataDTOTests()
        {
            // TODO uncomment below to create an instance of AudioUploadMetadataDTO
            //instance = new AudioUploadMetadataDTO();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AudioUploadMetadataDTO
        /// </summary>
        [Fact]
        public void AudioUploadMetadataDTOInstanceTest()
        {
            // TODO uncomment below to test "IsType" AudioUploadMetadataDTO
            //Assert.IsType<AudioUploadMetadataDTO>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Filename'
        /// </summary>
        [Fact]
        public void FilenameTest()
        {
            // TODO unit test for the property 'Filename'
        }

        /// <summary>
        /// Test the property 'Extension'
        /// </summary>
        [Fact]
        public void ExtensionTest()
        {
            // TODO unit test for the property 'Extension'
        }

        /// <summary>
        /// Test the property 'Size'
        /// </summary>
        [Fact]
        public void SizeTest()
        {
            // TODO unit test for the property 'Size'
        }

        /// <summary>
        /// Test the property 'AudioDuration'
        /// </summary>
        [Fact]
        public void AudioDurationTest()
        {
            // TODO unit test for the property 'AudioDuration'
        }

        /// <summary>
        /// Test the property 'NumberOfChannels'
        /// </summary>
        [Fact]
        public void NumberOfChannelsTest()
        {
            // TODO unit test for the property 'NumberOfChannels'
        }

        /// <summary>
        /// Test the property 'Source'
        /// </summary>
        [Fact]
        public void SourceTest()
        {
            // TODO unit test for the property 'Source'
        }
    }
}
