/*
 * Gladia Control API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Gladia.SDK.Model;
using Gladia.SDK.Client;
using System.Reflection;

namespace Gladia.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing CallbackConfig
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CallbackConfigTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CallbackConfig
        //private CallbackConfig instance;

        public CallbackConfigTests()
        {
            // TODO uncomment below to create an instance of CallbackConfig
            //instance = new CallbackConfig();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CallbackConfig
        /// </summary>
        [Fact]
        public void CallbackConfigInstanceTest()
        {
            // TODO uncomment below to test "IsType" CallbackConfig
            //Assert.IsType<CallbackConfig>(instance);
        }

        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

        /// <summary>
        /// Test the property 'ReceivePartialTranscripts'
        /// </summary>
        [Fact]
        public void ReceivePartialTranscriptsTest()
        {
            // TODO unit test for the property 'ReceivePartialTranscripts'
        }

        /// <summary>
        /// Test the property 'ReceiveFinalTranscripts'
        /// </summary>
        [Fact]
        public void ReceiveFinalTranscriptsTest()
        {
            // TODO unit test for the property 'ReceiveFinalTranscripts'
        }

        /// <summary>
        /// Test the property 'ReceiveSpeechEvents'
        /// </summary>
        [Fact]
        public void ReceiveSpeechEventsTest()
        {
            // TODO unit test for the property 'ReceiveSpeechEvents'
        }

        /// <summary>
        /// Test the property 'ReceivePreProcessingEvents'
        /// </summary>
        [Fact]
        public void ReceivePreProcessingEventsTest()
        {
            // TODO unit test for the property 'ReceivePreProcessingEvents'
        }

        /// <summary>
        /// Test the property 'ReceiveRealtimeProcessingEvents'
        /// </summary>
        [Fact]
        public void ReceiveRealtimeProcessingEventsTest()
        {
            // TODO unit test for the property 'ReceiveRealtimeProcessingEvents'
        }

        /// <summary>
        /// Test the property 'ReceivePostProcessingEvents'
        /// </summary>
        [Fact]
        public void ReceivePostProcessingEventsTest()
        {
            // TODO unit test for the property 'ReceivePostProcessingEvents'
        }

        /// <summary>
        /// Test the property 'ReceiveAcknowledgments'
        /// </summary>
        [Fact]
        public void ReceiveAcknowledgmentsTest()
        {
            // TODO unit test for the property 'ReceiveAcknowledgments'
        }

        /// <summary>
        /// Test the property 'ReceiveErrors'
        /// </summary>
        [Fact]
        public void ReceiveErrorsTest()
        {
            // TODO unit test for the property 'ReceiveErrors'
        }

        /// <summary>
        /// Test the property 'ReceiveLifecycleEvents'
        /// </summary>
        [Fact]
        public void ReceiveLifecycleEventsTest()
        {
            // TODO unit test for the property 'ReceiveLifecycleEvents'
        }
    }
}
