/*
 * Gladia Control API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Gladia.SDK.Model;
using Gladia.SDK.Client;
using System.Reflection;

namespace Gladia.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing CallbackTranscriptionSuccessPayload
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CallbackTranscriptionSuccessPayloadTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CallbackTranscriptionSuccessPayload
        //private CallbackTranscriptionSuccessPayload instance;

        public CallbackTranscriptionSuccessPayloadTests()
        {
            // TODO uncomment below to create an instance of CallbackTranscriptionSuccessPayload
            //instance = new CallbackTranscriptionSuccessPayload();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CallbackTranscriptionSuccessPayload
        /// </summary>
        [Fact]
        public void CallbackTranscriptionSuccessPayloadInstanceTest()
        {
            // TODO uncomment below to test "IsType" CallbackTranscriptionSuccessPayload
            //Assert.IsType<CallbackTranscriptionSuccessPayload>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Payload'
        /// </summary>
        [Fact]
        public void PayloadTest()
        {
            // TODO unit test for the property 'Payload'
        }

        /// <summary>
        /// Test the property 'Event'
        /// </summary>
        [Fact]
        public void EventTest()
        {
            // TODO unit test for the property 'Event'
        }

        /// <summary>
        /// Test the property 'CustomMetadata'
        /// </summary>
        [Fact]
        public void CustomMetadataTest()
        {
            // TODO unit test for the property 'CustomMetadata'
        }
    }
}
