/*
 * Gladia Control API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Gladia.SDK.Model;
using Gladia.SDK.Client;
using System.Reflection;

namespace Gladia.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing LanguageConfig
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LanguageConfigTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LanguageConfig
        //private LanguageConfig instance;

        public LanguageConfigTests()
        {
            // TODO uncomment below to create an instance of LanguageConfig
            //instance = new LanguageConfig();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LanguageConfig
        /// </summary>
        [Fact]
        public void LanguageConfigInstanceTest()
        {
            // TODO uncomment below to test "IsType" LanguageConfig
            //Assert.IsType<LanguageConfig>(instance);
        }

        /// <summary>
        /// Test the property 'Languages'
        /// </summary>
        [Fact]
        public void LanguagesTest()
        {
            // TODO unit test for the property 'Languages'
        }

        /// <summary>
        /// Test the property 'CodeSwitching'
        /// </summary>
        [Fact]
        public void CodeSwitchingTest()
        {
            // TODO unit test for the property 'CodeSwitching'
        }
    }
}
