/*
 * Gladia Control API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Gladia.SDK.Model;
using Gladia.SDK.Client;
using System.Reflection;

namespace Gladia.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing ListPreRecordedResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ListPreRecordedResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ListPreRecordedResponse
        //private ListPreRecordedResponse instance;

        public ListPreRecordedResponseTests()
        {
            // TODO uncomment below to create an instance of ListPreRecordedResponse
            //instance = new ListPreRecordedResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ListPreRecordedResponse
        /// </summary>
        [Fact]
        public void ListPreRecordedResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ListPreRecordedResponse
            //Assert.IsType<ListPreRecordedResponse>(instance);
        }

        /// <summary>
        /// Test the property 'First'
        /// </summary>
        [Fact]
        public void FirstTest()
        {
            // TODO unit test for the property 'First'
        }

        /// <summary>
        /// Test the property 'Current'
        /// </summary>
        [Fact]
        public void CurrentTest()
        {
            // TODO unit test for the property 'Current'
        }

        /// <summary>
        /// Test the property 'Next'
        /// </summary>
        [Fact]
        public void NextTest()
        {
            // TODO unit test for the property 'Next'
        }

        /// <summary>
        /// Test the property 'Items'
        /// </summary>
        [Fact]
        public void ItemsTest()
        {
            // TODO unit test for the property 'Items'
        }
    }
}
