/*
 * Gladia Control API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Gladia.SDK.Model;
using Gladia.SDK.Client;
using System.Reflection;

namespace Gladia.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing StreamingTranscriptionResultWithMessagesDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StreamingTranscriptionResultWithMessagesDTOTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for StreamingTranscriptionResultWithMessagesDTO
        //private StreamingTranscriptionResultWithMessagesDTO instance;

        public StreamingTranscriptionResultWithMessagesDTOTests()
        {
            // TODO uncomment below to create an instance of StreamingTranscriptionResultWithMessagesDTO
            //instance = new StreamingTranscriptionResultWithMessagesDTO();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of StreamingTranscriptionResultWithMessagesDTO
        /// </summary>
        [Fact]
        public void StreamingTranscriptionResultWithMessagesDTOInstanceTest()
        {
            // TODO uncomment below to test "IsType" StreamingTranscriptionResultWithMessagesDTO
            //Assert.IsType<StreamingTranscriptionResultWithMessagesDTO>(instance);
        }

        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }

        /// <summary>
        /// Test the property 'Transcription'
        /// </summary>
        [Fact]
        public void TranscriptionTest()
        {
            // TODO unit test for the property 'Transcription'
        }

        /// <summary>
        /// Test the property 'Translation'
        /// </summary>
        [Fact]
        public void TranslationTest()
        {
            // TODO unit test for the property 'Translation'
        }

        /// <summary>
        /// Test the property 'Summarization'
        /// </summary>
        [Fact]
        public void SummarizationTest()
        {
            // TODO unit test for the property 'Summarization'
        }

        /// <summary>
        /// Test the property 'NamedEntityRecognition'
        /// </summary>
        [Fact]
        public void NamedEntityRecognitionTest()
        {
            // TODO unit test for the property 'NamedEntityRecognition'
        }

        /// <summary>
        /// Test the property 'SentimentAnalysis'
        /// </summary>
        [Fact]
        public void SentimentAnalysisTest()
        {
            // TODO unit test for the property 'SentimentAnalysis'
        }

        /// <summary>
        /// Test the property 'Chapterization'
        /// </summary>
        [Fact]
        public void ChapterizationTest()
        {
            // TODO unit test for the property 'Chapterization'
        }

        /// <summary>
        /// Test the property 'Messages'
        /// </summary>
        [Fact]
        public void MessagesTest()
        {
            // TODO unit test for the property 'Messages'
        }
    }
}
