/*
 * Gladia Control API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Gladia.SDK.Model;
using Gladia.SDK.Client;
using System.Reflection;

namespace Gladia.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing StreamingSupportedModels
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StreamingSupportedModelsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for StreamingSupportedModels
        //private StreamingSupportedModels instance;

        public StreamingSupportedModelsTests()
        {
            // TODO uncomment below to create an instance of StreamingSupportedModels
            //instance = new StreamingSupportedModels();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of StreamingSupportedModels
        /// </summary>
        [Fact]
        public void StreamingSupportedModelsInstanceTest()
        {
            // TODO uncomment below to test "IsType" StreamingSupportedModels
            //Assert.IsType<StreamingSupportedModels>(instance);
        }
    }
}
