/*
 * Gladia Control API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Gladia.SDK.Model;
using Gladia.SDK.Client;
using System.Reflection;

namespace Gladia.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing TranslationConfigDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TranslationConfigDTOTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TranslationConfigDTO
        //private TranslationConfigDTO instance;

        public TranslationConfigDTOTests()
        {
            // TODO uncomment below to create an instance of TranslationConfigDTO
            //instance = new TranslationConfigDTO();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TranslationConfigDTO
        /// </summary>
        [Fact]
        public void TranslationConfigDTOInstanceTest()
        {
            // TODO uncomment below to test "IsType" TranslationConfigDTO
            //Assert.IsType<TranslationConfigDTO>(instance);
        }

        /// <summary>
        /// Test the property 'TargetLanguages'
        /// </summary>
        [Fact]
        public void TargetLanguagesTest()
        {
            // TODO unit test for the property 'TargetLanguages'
        }

        /// <summary>
        /// Test the property 'Model'
        /// </summary>
        [Fact]
        public void ModelTest()
        {
            // TODO unit test for the property 'Model'
        }

        /// <summary>
        /// Test the property 'MatchOriginalUtterances'
        /// </summary>
        [Fact]
        public void MatchOriginalUtterancesTest()
        {
            // TODO unit test for the property 'MatchOriginalUtterances'
        }

        /// <summary>
        /// Test the property 'Lipsync'
        /// </summary>
        [Fact]
        public void LipsyncTest()
        {
            // TODO unit test for the property 'Lipsync'
        }

        /// <summary>
        /// Test the property 'ContextAdaptation'
        /// </summary>
        [Fact]
        public void ContextAdaptationTest()
        {
            // TODO unit test for the property 'ContextAdaptation'
        }

        /// <summary>
        /// Test the property 'Context'
        /// </summary>
        [Fact]
        public void ContextTest()
        {
            // TODO unit test for the property 'Context'
        }

        /// <summary>
        /// Test the property 'Informal'
        /// </summary>
        [Fact]
        public void InformalTest()
        {
            // TODO unit test for the property 'Informal'
        }
    }
}
