/**
 * Validation utilities for Voice Router SDK
 *
 * Provides generic validators for OpenAPI-generated enum types,
 * ensuring type-safe validation across all providers.
 */

/**
 * Validate that a value is a member of an OpenAPI-generated enum
 *
 * This generic validator works with any enum type generated by Orval from
 * OpenAPI specifications, providing consistent validation and error messages.
 *
 * @param value - Value to validate
 * @param enumType - OpenAPI-generated enum object
 * @param fieldName - Human-readable field name for error messages
 * @param provider - Provider name for error messages
 * @returns The validated value, properly typed as the enum type
 * @throws Error if value is not in the enum
 *
 * @example Validate Gladia sample rate
 * ```typescript
 * import { StreamingSupportedSampleRateEnum } from "../generated/gladia/schema/streamingSupportedSampleRateEnum"
 *
 * const validatedRate = validateEnumValue(
 *   16000,
 *   StreamingSupportedSampleRateEnum,
 *   "sample rate",
 *   "Gladia"
 * )
 * // Returns: 16000 (typed as StreamingSupportedSampleRateEnum)
 *
 * validateEnumValue(
 *   22050,
 *   StreamingSupportedSampleRateEnum,
 *   "sample rate",
 *   "Gladia"
 * )
 * // Throws: "Gladia does not support sample rate '22050'. Supported values (from OpenAPI spec): 8000, 16000, 32000, 44100, 48000"
 * ```
 *
 * @example Validate Deepgram encoding
 * ```typescript
 * import { ListenV1EncodingParameter } from "../generated/deepgram/schema/listenV1EncodingParameter"
 *
 * const encoding = validateEnumValue(
 *   "linear16",
 *   ListenV1EncodingParameter,
 *   "encoding",
 *   "Deepgram"
 * )
 * ```
 */
export function validateEnumValue<T extends Record<string, string | number>>(
  value: unknown,
  enumType: T,
  fieldName: string,
  provider: string
): T[keyof T] {
  const validValues = Object.values(enumType)
  const isValid = validValues.some((v) => v === value)

  if (!isValid) {
    throw new Error(
      `${provider} does not support ${fieldName} '${value}'. ` +
        `Supported values (from OpenAPI spec): ${validValues.join(", ")}`
    )
  }

  return value as T[keyof T]
}

/**
 * Validate optional enum value
 *
 * Like validateEnumValue but returns undefined if value is nullish,
 * useful for optional configuration parameters.
 *
 * @param value - Value to validate (can be undefined/null)
 * @param enumType - OpenAPI-generated enum object
 * @param fieldName - Human-readable field name for error messages
 * @param provider - Provider name for error messages
 * @returns The validated value or undefined
 * @throws Error if value is not in the enum (but not if undefined/null)
 *
 * @example
 * ```typescript
 * const rate = validateOptionalEnumValue(
 *   options?.sampleRate,
 *   StreamingSupportedSampleRateEnum,
 *   "sample rate",
 *   "Gladia"
 * )
 * // Returns: validated rate or undefined
 * ```
 */
export function validateOptionalEnumValue<T extends Record<string, string | number>>(
  value: unknown,
  enumType: T,
  fieldName: string,
  provider: string
): T[keyof T] | undefined {
  if (value === undefined || value === null) {
    return undefined
  }

  return validateEnumValue(value, enumType, fieldName, provider)
}
