/*
 * Gladia Control API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using Gladia.SDK.Api;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace Gladia.SDK.Test.Api
{
    /// <summary>
    ///  Class for testing AudioToTextApi
    /// </summary>
    public sealed class AudioToTextApiTests : ApiTestsBase
    {
        private readonly IAudioToTextApi _instance;

        public AudioToTextApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<IAudioToTextApi>();
        }

        /// <summary>
        /// Test AudioToTextControllerAudioTranscription
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task AudioToTextControllerAudioTranscriptionAsyncTest()
        {
            Client.Option<System.IO.Stream> audio = default!;
            Client.Option<string> audioUrl = default!;
            Client.Option<string> languageBehaviour = default!;
            Client.Option<string> language = default!;
            Client.Option<string> transcriptionHint = default!;
            Client.Option<bool> toggleDiarization = default!;
            Client.Option<int> diarizationNumSpeakers = default!;
            Client.Option<int> diarizationMinSpeakers = default!;
            Client.Option<int> diarizationMaxSpeakers = default!;
            Client.Option<bool> toggleDirectTranslate = default!;
            Client.Option<string> targetTranslationLanguage = default!;
            Client.Option<string> outputFormat = default!;
            Client.Option<bool> toggleNoiseReduction = default!;
            Client.Option<bool> toggleAccurateWordsTimestamps = default!;
            Client.Option<string> webhookUrl = default!;
            await _instance.AudioToTextControllerAudioTranscriptionAsync(audio, audioUrl, languageBehaviour, language, transcriptionHint, toggleDiarization, diarizationNumSpeakers, diarizationMinSpeakers, diarizationMaxSpeakers, toggleDirectTranslate, targetTranslationLanguage, outputFormat, toggleNoiseReduction, toggleAccurateWordsTimestamps, webhookUrl);
        }
    }
}
