/*
 * Gladia Control API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using Gladia.SDK.Api;
using Gladia.SDK.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace Gladia.SDK.Test.Api
{
    /// <summary>
    ///  Class for testing FileManagementApi
    /// </summary>
    public sealed class FileManagementApiTests : ApiTestsBase
    {
        private readonly IFileManagementApi _instance;

        public FileManagementApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<IFileManagementApi>();
        }

        /// <summary>
        /// Test FileControllerUploadV2
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task FileControllerUploadV2AsyncTest()
        {
            Client.Option<System.IO.Stream> audio = default!;
            var response = await _instance.FileControllerUploadV2Async(audio);
            var model = response.Ok();
            Assert.IsType<AudioUploadResponse>(model);
        }
    }
}
