// <auto-generated>
/*
 * Gladia Control API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Gladia.SDK.Client;

namespace Gladia.SDK.Model
{
    /// <summary>
    /// AddonErrorDTO
    /// </summary>
    public partial class AddonErrorDTO : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AddonErrorDTO" /> class.
        /// </summary>
        /// <param name="statusCode">Status code of the addon error</param>
        /// <param name="exception">Reason of the addon error</param>
        /// <param name="message">Detailed message of the addon error</param>
        [JsonConstructor]
        public AddonErrorDTO(int statusCode, string exception, string message)
        {
            StatusCode = statusCode;
            Exception = exception;
            Message = message;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Status code of the addon error
        /// </summary>
        /// <value>Status code of the addon error</value>
        /* <example>500</example> */
        [JsonPropertyName("status_code")]
        public int StatusCode { get; set; }

        /// <summary>
        /// Reason of the addon error
        /// </summary>
        /// <value>Reason of the addon error</value>
        [JsonPropertyName("exception")]
        public string Exception { get; set; }

        /// <summary>
        /// Detailed message of the addon error
        /// </summary>
        /// <value>Detailed message of the addon error</value>
        [JsonPropertyName("message")]
        public string Message { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AddonErrorDTO {\n");
            sb.Append("  StatusCode: ").Append(StatusCode).Append("\n");
            sb.Append("  Exception: ").Append(Exception).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="AddonErrorDTO" />
    /// </summary>
    public class AddonErrorDTOJsonConverter : JsonConverter<AddonErrorDTO>
    {
        /// <summary>
        /// Deserializes json to <see cref="AddonErrorDTO" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override AddonErrorDTO Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> statusCode = default;
            Option<string?> exception = default;
            Option<string?> message = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "status_code":
                            statusCode = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "exception":
                            exception = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "message":
                            message = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!statusCode.IsSet)
                throw new ArgumentException("Property is required for class AddonErrorDTO.", nameof(statusCode));

            if (!exception.IsSet)
                throw new ArgumentException("Property is required for class AddonErrorDTO.", nameof(exception));

            if (!message.IsSet)
                throw new ArgumentException("Property is required for class AddonErrorDTO.", nameof(message));

            if (statusCode.IsSet && statusCode.Value == null)
                throw new ArgumentNullException(nameof(statusCode), "Property is not nullable for class AddonErrorDTO.");

            if (exception.IsSet && exception.Value == null)
                throw new ArgumentNullException(nameof(exception), "Property is not nullable for class AddonErrorDTO.");

            if (message.IsSet && message.Value == null)
                throw new ArgumentNullException(nameof(message), "Property is not nullable for class AddonErrorDTO.");

            return new AddonErrorDTO(statusCode.Value!.Value!, exception.Value!, message.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="AddonErrorDTO" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="addonErrorDTO"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, AddonErrorDTO addonErrorDTO, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, addonErrorDTO, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="AddonErrorDTO" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="addonErrorDTO"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, AddonErrorDTO addonErrorDTO, JsonSerializerOptions jsonSerializerOptions)
        {
            if (addonErrorDTO.Exception == null)
                throw new ArgumentNullException(nameof(addonErrorDTO.Exception), "Property is required for class AddonErrorDTO.");

            if (addonErrorDTO.Message == null)
                throw new ArgumentNullException(nameof(addonErrorDTO.Message), "Property is required for class AddonErrorDTO.");

            writer.WriteNumber("status_code", addonErrorDTO.StatusCode);

            writer.WriteString("exception", addonErrorDTO.Exception);

            writer.WriteString("message", addonErrorDTO.Message);
        }
    }
}
