// <auto-generated>
/*
 * Gladia Control API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Gladia.SDK.Client;

namespace Gladia.SDK.Model
{
    /// <summary>
    /// AudioUploadResponse
    /// </summary>
    public partial class AudioUploadResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AudioUploadResponse" /> class.
        /// </summary>
        /// <param name="audioUrl">Uploaded audio file Gladia URL</param>
        /// <param name="audioMetadata">Uploaded audio file detected metadata</param>
        [JsonConstructor]
        public AudioUploadResponse(string audioUrl, AudioUploadMetadataDTO audioMetadata)
        {
            AudioUrl = audioUrl;
            AudioMetadata = audioMetadata;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Uploaded audio file Gladia URL
        /// </summary>
        /// <value>Uploaded audio file Gladia URL</value>
        /* <example>https://api.gladia.io/file/6c09400e-23d2-4bd2-be55-96a5ececfa3b</example> */
        [JsonPropertyName("audio_url")]
        public string AudioUrl { get; set; }

        /// <summary>
        /// Uploaded audio file detected metadata
        /// </summary>
        /// <value>Uploaded audio file detected metadata</value>
        [JsonPropertyName("audio_metadata")]
        public AudioUploadMetadataDTO AudioMetadata { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AudioUploadResponse {\n");
            sb.Append("  AudioUrl: ").Append(AudioUrl).Append("\n");
            sb.Append("  AudioMetadata: ").Append(AudioMetadata).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="AudioUploadResponse" />
    /// </summary>
    public class AudioUploadResponseJsonConverter : JsonConverter<AudioUploadResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="AudioUploadResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override AudioUploadResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> audioUrl = default;
            Option<AudioUploadMetadataDTO?> audioMetadata = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "audio_url":
                            audioUrl = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "audio_metadata":
                            audioMetadata = new Option<AudioUploadMetadataDTO?>(JsonSerializer.Deserialize<AudioUploadMetadataDTO>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!audioUrl.IsSet)
                throw new ArgumentException("Property is required for class AudioUploadResponse.", nameof(audioUrl));

            if (!audioMetadata.IsSet)
                throw new ArgumentException("Property is required for class AudioUploadResponse.", nameof(audioMetadata));

            if (audioUrl.IsSet && audioUrl.Value == null)
                throw new ArgumentNullException(nameof(audioUrl), "Property is not nullable for class AudioUploadResponse.");

            if (audioMetadata.IsSet && audioMetadata.Value == null)
                throw new ArgumentNullException(nameof(audioMetadata), "Property is not nullable for class AudioUploadResponse.");

            return new AudioUploadResponse(audioUrl.Value!, audioMetadata.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="AudioUploadResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="audioUploadResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, AudioUploadResponse audioUploadResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, audioUploadResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="AudioUploadResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="audioUploadResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, AudioUploadResponse audioUploadResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (audioUploadResponse.AudioUrl == null)
                throw new ArgumentNullException(nameof(audioUploadResponse.AudioUrl), "Property is required for class AudioUploadResponse.");

            if (audioUploadResponse.AudioMetadata == null)
                throw new ArgumentNullException(nameof(audioUploadResponse.AudioMetadata), "Property is required for class AudioUploadResponse.");

            writer.WriteString("audio_url", audioUploadResponse.AudioUrl);

            writer.WritePropertyName("audio_metadata");
            JsonSerializer.Serialize(writer, audioUploadResponse.AudioMetadata, jsonSerializerOptions);
        }
    }
}
