// <auto-generated>
/*
 * Gladia Control API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Gladia.SDK.Client;

namespace Gladia.SDK.Model
{
    /// <summary>
    /// AudioChunkAckData
    /// </summary>
    public partial class AudioChunkAckData : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AudioChunkAckData" /> class.
        /// </summary>
        /// <param name="byteRange">Range in bytes length of the audio chunk (relative to the whole session)</param>
        /// <param name="timeRange">Range in seconds of the audio chunk (relative to the whole session)</param>
        [JsonConstructor]
        public AudioChunkAckData(List<int> byteRange, List<decimal> timeRange)
        {
            ByteRange = byteRange;
            TimeRange = timeRange;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Range in bytes length of the audio chunk (relative to the whole session)
        /// </summary>
        /// <value>Range in bytes length of the audio chunk (relative to the whole session)</value>
        /* <example>[1024, 2048]</example> */
        [JsonPropertyName("byte_range")]
        public List<int> ByteRange { get; set; }

        /// <summary>
        /// Range in seconds of the audio chunk (relative to the whole session)
        /// </summary>
        /// <value>Range in seconds of the audio chunk (relative to the whole session)</value>
        /* <example>[0.8, 0.9]</example> */
        [JsonPropertyName("time_range")]
        public List<decimal> TimeRange { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AudioChunkAckData {\n");
            sb.Append("  ByteRange: ").Append(ByteRange).Append("\n");
            sb.Append("  TimeRange: ").Append(TimeRange).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="AudioChunkAckData" />
    /// </summary>
    public class AudioChunkAckDataJsonConverter : JsonConverter<AudioChunkAckData>
    {
        /// <summary>
        /// Deserializes json to <see cref="AudioChunkAckData" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override AudioChunkAckData Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<int>?> byteRange = default;
            Option<List<decimal>?> timeRange = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "byte_range":
                            byteRange = new Option<List<int>?>(JsonSerializer.Deserialize<List<int>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "time_range":
                            timeRange = new Option<List<decimal>?>(JsonSerializer.Deserialize<List<decimal>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!byteRange.IsSet)
                throw new ArgumentException("Property is required for class AudioChunkAckData.", nameof(byteRange));

            if (!timeRange.IsSet)
                throw new ArgumentException("Property is required for class AudioChunkAckData.", nameof(timeRange));

            if (byteRange.IsSet && byteRange.Value == null)
                throw new ArgumentNullException(nameof(byteRange), "Property is not nullable for class AudioChunkAckData.");

            if (timeRange.IsSet && timeRange.Value == null)
                throw new ArgumentNullException(nameof(timeRange), "Property is not nullable for class AudioChunkAckData.");

            return new AudioChunkAckData(byteRange.Value!, timeRange.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="AudioChunkAckData" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="audioChunkAckData"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, AudioChunkAckData audioChunkAckData, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, audioChunkAckData, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="AudioChunkAckData" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="audioChunkAckData"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, AudioChunkAckData audioChunkAckData, JsonSerializerOptions jsonSerializerOptions)
        {
            if (audioChunkAckData.ByteRange == null)
                throw new ArgumentNullException(nameof(audioChunkAckData.ByteRange), "Property is required for class AudioChunkAckData.");

            if (audioChunkAckData.TimeRange == null)
                throw new ArgumentNullException(nameof(audioChunkAckData.TimeRange), "Property is required for class AudioChunkAckData.");

            writer.WritePropertyName("byte_range");
            JsonSerializer.Serialize(writer, audioChunkAckData.ByteRange, jsonSerializerOptions);
            writer.WritePropertyName("time_range");
            JsonSerializer.Serialize(writer, audioChunkAckData.TimeRange, jsonSerializerOptions);
        }
    }
}
