// <auto-generated>
/*
 * Gladia Control API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Gladia.SDK.Client;

namespace Gladia.SDK.Model
{
    /// <summary>
    /// CallbackLiveSentimentAnalysisMessage
    /// </summary>
    public partial class CallbackLiveSentimentAnalysisMessage : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CallbackLiveSentimentAnalysisMessage" /> class.
        /// </summary>
        /// <param name="id">Id of the job</param>
        /// <param name="payload">The live message payload as sent to the WebSocket</param>
        /// <param name="event">event (default to EventEnum.LiveSentimentAnalysis)</param>
        [JsonConstructor]
        public CallbackLiveSentimentAnalysisMessage(Guid id, SentimentAnalysisMessage payload, EventEnum @event = EventEnum.LiveSentimentAnalysis)
        {
            Id = id;
            Payload = payload;
            Event = @event;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines Event
        /// </summary>
        public enum EventEnum
        {
            /// <summary>
            /// Enum LiveSentimentAnalysis for value: live.sentiment_analysis
            /// </summary>
            LiveSentimentAnalysis = 1
        }

        /// <summary>
        /// Returns a <see cref="EventEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static EventEnum EventEnumFromString(string value)
        {
            if (value.Equals("live.sentiment_analysis"))
                return EventEnum.LiveSentimentAnalysis;

            throw new NotImplementedException($"Could not convert value to type EventEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="EventEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static EventEnum? EventEnumFromStringOrDefault(string value)
        {
            if (value.Equals("live.sentiment_analysis"))
                return EventEnum.LiveSentimentAnalysis;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="EventEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string EventEnumToJsonValue(EventEnum value)
        {
            if (value == EventEnum.LiveSentimentAnalysis)
                return "live.sentiment_analysis";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Gets or Sets Event
        /// </summary>
        /* <example>live.sentiment_analysis</example> */
        [JsonPropertyName("event")]
        public EventEnum Event { get; set; }

        /// <summary>
        /// Id of the job
        /// </summary>
        /// <value>Id of the job</value>
        /* <example>45463597-20b7-4af7-b3b3-f5fb778203ab</example> */
        [JsonPropertyName("id")]
        public Guid Id { get; set; }

        /// <summary>
        /// The live message payload as sent to the WebSocket
        /// </summary>
        /// <value>The live message payload as sent to the WebSocket</value>
        [JsonPropertyName("payload")]
        public SentimentAnalysisMessage Payload { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CallbackLiveSentimentAnalysisMessage {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Payload: ").Append(Payload).Append("\n");
            sb.Append("  Event: ").Append(Event).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CallbackLiveSentimentAnalysisMessage" />
    /// </summary>
    public class CallbackLiveSentimentAnalysisMessageJsonConverter : JsonConverter<CallbackLiveSentimentAnalysisMessage>
    {
        /// <summary>
        /// Deserializes json to <see cref="CallbackLiveSentimentAnalysisMessage" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CallbackLiveSentimentAnalysisMessage Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Guid?> id = default;
            Option<SentimentAnalysisMessage?> payload = default;
            Option<CallbackLiveSentimentAnalysisMessage.EventEnum?> varEvent = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "payload":
                            payload = new Option<SentimentAnalysisMessage?>(JsonSerializer.Deserialize<SentimentAnalysisMessage>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "event":
                            string? varEventRawValue = utf8JsonReader.GetString();
                            if (varEventRawValue != null)
                                varEvent = new Option<CallbackLiveSentimentAnalysisMessage.EventEnum?>(CallbackLiveSentimentAnalysisMessage.EventEnumFromStringOrDefault(varEventRawValue));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class CallbackLiveSentimentAnalysisMessage.", nameof(id));

            if (!payload.IsSet)
                throw new ArgumentException("Property is required for class CallbackLiveSentimentAnalysisMessage.", nameof(payload));

            if (!varEvent.IsSet)
                throw new ArgumentException("Property is required for class CallbackLiveSentimentAnalysisMessage.", nameof(varEvent));

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class CallbackLiveSentimentAnalysisMessage.");

            if (payload.IsSet && payload.Value == null)
                throw new ArgumentNullException(nameof(payload), "Property is not nullable for class CallbackLiveSentimentAnalysisMessage.");

            if (varEvent.IsSet && varEvent.Value == null)
                throw new ArgumentNullException(nameof(varEvent), "Property is not nullable for class CallbackLiveSentimentAnalysisMessage.");

            return new CallbackLiveSentimentAnalysisMessage(id.Value!.Value!, payload.Value!, varEvent.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="CallbackLiveSentimentAnalysisMessage" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="callbackLiveSentimentAnalysisMessage"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, CallbackLiveSentimentAnalysisMessage callbackLiveSentimentAnalysisMessage, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, callbackLiveSentimentAnalysisMessage, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CallbackLiveSentimentAnalysisMessage" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="callbackLiveSentimentAnalysisMessage"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, CallbackLiveSentimentAnalysisMessage callbackLiveSentimentAnalysisMessage, JsonSerializerOptions jsonSerializerOptions)
        {
            if (callbackLiveSentimentAnalysisMessage.Payload == null)
                throw new ArgumentNullException(nameof(callbackLiveSentimentAnalysisMessage.Payload), "Property is required for class CallbackLiveSentimentAnalysisMessage.");

            writer.WriteString("id", callbackLiveSentimentAnalysisMessage.Id);

            writer.WritePropertyName("payload");
            JsonSerializer.Serialize(writer, callbackLiveSentimentAnalysisMessage.Payload, jsonSerializerOptions);
            var varEventRawValue = CallbackLiveSentimentAnalysisMessage.EventEnumToJsonValue(callbackLiveSentimentAnalysisMessage.Event);
            writer.WriteString("event", varEventRawValue);
        }
    }
}
