// <auto-generated>
/*
 * Gladia Control API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Gladia.SDK.Client;

namespace Gladia.SDK.Model
{
    /// <summary>
    /// CallbackLiveSpeechEndMessage
    /// </summary>
    public partial class CallbackLiveSpeechEndMessage : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CallbackLiveSpeechEndMessage" /> class.
        /// </summary>
        /// <param name="id">Id of the job</param>
        /// <param name="payload">The live message payload as sent to the WebSocket</param>
        /// <param name="event">event (default to EventEnum.LiveSpeechEnd)</param>
        [JsonConstructor]
        public CallbackLiveSpeechEndMessage(Guid id, SpeechEndMessage payload, EventEnum @event = EventEnum.LiveSpeechEnd)
        {
            Id = id;
            Payload = payload;
            Event = @event;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines Event
        /// </summary>
        public enum EventEnum
        {
            /// <summary>
            /// Enum LiveSpeechEnd for value: live.speech_end
            /// </summary>
            LiveSpeechEnd = 1
        }

        /// <summary>
        /// Returns a <see cref="EventEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static EventEnum EventEnumFromString(string value)
        {
            if (value.Equals("live.speech_end"))
                return EventEnum.LiveSpeechEnd;

            throw new NotImplementedException($"Could not convert value to type EventEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="EventEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static EventEnum? EventEnumFromStringOrDefault(string value)
        {
            if (value.Equals("live.speech_end"))
                return EventEnum.LiveSpeechEnd;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="EventEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string EventEnumToJsonValue(EventEnum value)
        {
            if (value == EventEnum.LiveSpeechEnd)
                return "live.speech_end";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Gets or Sets Event
        /// </summary>
        /* <example>live.speech_end</example> */
        [JsonPropertyName("event")]
        public EventEnum Event { get; set; }

        /// <summary>
        /// Id of the job
        /// </summary>
        /// <value>Id of the job</value>
        /* <example>45463597-20b7-4af7-b3b3-f5fb778203ab</example> */
        [JsonPropertyName("id")]
        public Guid Id { get; set; }

        /// <summary>
        /// The live message payload as sent to the WebSocket
        /// </summary>
        /// <value>The live message payload as sent to the WebSocket</value>
        [JsonPropertyName("payload")]
        public SpeechEndMessage Payload { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CallbackLiveSpeechEndMessage {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Payload: ").Append(Payload).Append("\n");
            sb.Append("  Event: ").Append(Event).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CallbackLiveSpeechEndMessage" />
    /// </summary>
    public class CallbackLiveSpeechEndMessageJsonConverter : JsonConverter<CallbackLiveSpeechEndMessage>
    {
        /// <summary>
        /// Deserializes json to <see cref="CallbackLiveSpeechEndMessage" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CallbackLiveSpeechEndMessage Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Guid?> id = default;
            Option<SpeechEndMessage?> payload = default;
            Option<CallbackLiveSpeechEndMessage.EventEnum?> varEvent = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "payload":
                            payload = new Option<SpeechEndMessage?>(JsonSerializer.Deserialize<SpeechEndMessage>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "event":
                            string? varEventRawValue = utf8JsonReader.GetString();
                            if (varEventRawValue != null)
                                varEvent = new Option<CallbackLiveSpeechEndMessage.EventEnum?>(CallbackLiveSpeechEndMessage.EventEnumFromStringOrDefault(varEventRawValue));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class CallbackLiveSpeechEndMessage.", nameof(id));

            if (!payload.IsSet)
                throw new ArgumentException("Property is required for class CallbackLiveSpeechEndMessage.", nameof(payload));

            if (!varEvent.IsSet)
                throw new ArgumentException("Property is required for class CallbackLiveSpeechEndMessage.", nameof(varEvent));

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class CallbackLiveSpeechEndMessage.");

            if (payload.IsSet && payload.Value == null)
                throw new ArgumentNullException(nameof(payload), "Property is not nullable for class CallbackLiveSpeechEndMessage.");

            if (varEvent.IsSet && varEvent.Value == null)
                throw new ArgumentNullException(nameof(varEvent), "Property is not nullable for class CallbackLiveSpeechEndMessage.");

            return new CallbackLiveSpeechEndMessage(id.Value!.Value!, payload.Value!, varEvent.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="CallbackLiveSpeechEndMessage" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="callbackLiveSpeechEndMessage"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, CallbackLiveSpeechEndMessage callbackLiveSpeechEndMessage, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, callbackLiveSpeechEndMessage, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CallbackLiveSpeechEndMessage" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="callbackLiveSpeechEndMessage"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, CallbackLiveSpeechEndMessage callbackLiveSpeechEndMessage, JsonSerializerOptions jsonSerializerOptions)
        {
            if (callbackLiveSpeechEndMessage.Payload == null)
                throw new ArgumentNullException(nameof(callbackLiveSpeechEndMessage.Payload), "Property is required for class CallbackLiveSpeechEndMessage.");

            writer.WriteString("id", callbackLiveSpeechEndMessage.Id);

            writer.WritePropertyName("payload");
            JsonSerializer.Serialize(writer, callbackLiveSpeechEndMessage.Payload, jsonSerializerOptions);
            var varEventRawValue = CallbackLiveSpeechEndMessage.EventEnumToJsonValue(callbackLiveSpeechEndMessage.Event);
            writer.WriteString("event", varEventRawValue);
        }
    }
}
