// <auto-generated>
/*
 * Gladia Control API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Gladia.SDK.Client;

namespace Gladia.SDK.Model
{
    /// <summary>
    /// CodeSwitchingConfigDTO
    /// </summary>
    public partial class CodeSwitchingConfigDTO : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CodeSwitchingConfigDTO" /> class.
        /// </summary>
        /// <param name="languages">Specify the languages you want to use when detecting multiple languages</param>
        [JsonConstructor]
        public CodeSwitchingConfigDTO(Option<List<TranscriptionLanguageCodeEnum>?> languages = default)
        {
            LanguagesOption = languages;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Languages
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<TranscriptionLanguageCodeEnum>?> LanguagesOption { get; private set; }

        /// <summary>
        /// Specify the languages you want to use when detecting multiple languages
        /// </summary>
        /// <value>Specify the languages you want to use when detecting multiple languages</value>
        [JsonPropertyName("languages")]
        public List<TranscriptionLanguageCodeEnum>? Languages { get { return this.LanguagesOption; } set { this.LanguagesOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CodeSwitchingConfigDTO {\n");
            sb.Append("  Languages: ").Append(Languages).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CodeSwitchingConfigDTO" />
    /// </summary>
    public class CodeSwitchingConfigDTOJsonConverter : JsonConverter<CodeSwitchingConfigDTO>
    {
        /// <summary>
        /// Deserializes json to <see cref="CodeSwitchingConfigDTO" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CodeSwitchingConfigDTO Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<TranscriptionLanguageCodeEnum>?> languages = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "languages":
                            languages = new Option<List<TranscriptionLanguageCodeEnum>?>(JsonSerializer.Deserialize<List<TranscriptionLanguageCodeEnum>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (languages.IsSet && languages.Value == null)
                throw new ArgumentNullException(nameof(languages), "Property is not nullable for class CodeSwitchingConfigDTO.");

            return new CodeSwitchingConfigDTO(languages);
        }

        /// <summary>
        /// Serializes a <see cref="CodeSwitchingConfigDTO" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="codeSwitchingConfigDTO"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, CodeSwitchingConfigDTO codeSwitchingConfigDTO, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, codeSwitchingConfigDTO, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CodeSwitchingConfigDTO" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="codeSwitchingConfigDTO"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, CodeSwitchingConfigDTO codeSwitchingConfigDTO, JsonSerializerOptions jsonSerializerOptions)
        {
            if (codeSwitchingConfigDTO.LanguagesOption.IsSet && codeSwitchingConfigDTO.Languages == null)
                throw new ArgumentNullException(nameof(codeSwitchingConfigDTO.Languages), "Property is required for class CodeSwitchingConfigDTO.");

            if (codeSwitchingConfigDTO.LanguagesOption.IsSet)
            {
                writer.WritePropertyName("languages");
                JsonSerializer.Serialize(writer, codeSwitchingConfigDTO.Languages, jsonSerializerOptions);
            }
        }
    }
}
