// <auto-generated>
/*
 * Gladia Control API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Gladia.SDK.Client;

namespace Gladia.SDK.Model
{
    /// <summary>
    /// NamedEntityRecognitionResult
    /// </summary>
    public partial class NamedEntityRecognitionResult : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NamedEntityRecognitionResult" /> class.
        /// </summary>
        /// <param name="entityType">entityType</param>
        /// <param name="text">text</param>
        /// <param name="start">start</param>
        /// <param name="end">end</param>
        [JsonConstructor]
        public NamedEntityRecognitionResult(string entityType, string text, decimal start, decimal end)
        {
            EntityType = entityType;
            Text = text;
            Start = start;
            End = end;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets EntityType
        /// </summary>
        [JsonPropertyName("entity_type")]
        public string EntityType { get; set; }

        /// <summary>
        /// Gets or Sets Text
        /// </summary>
        [JsonPropertyName("text")]
        public string Text { get; set; }

        /// <summary>
        /// Gets or Sets Start
        /// </summary>
        [JsonPropertyName("start")]
        public decimal Start { get; set; }

        /// <summary>
        /// Gets or Sets End
        /// </summary>
        [JsonPropertyName("end")]
        public decimal End { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class NamedEntityRecognitionResult {\n");
            sb.Append("  EntityType: ").Append(EntityType).Append("\n");
            sb.Append("  Text: ").Append(Text).Append("\n");
            sb.Append("  Start: ").Append(Start).Append("\n");
            sb.Append("  End: ").Append(End).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="NamedEntityRecognitionResult" />
    /// </summary>
    public class NamedEntityRecognitionResultJsonConverter : JsonConverter<NamedEntityRecognitionResult>
    {
        /// <summary>
        /// Deserializes json to <see cref="NamedEntityRecognitionResult" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override NamedEntityRecognitionResult Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> entityType = default;
            Option<string?> text = default;
            Option<decimal?> start = default;
            Option<decimal?> end = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "entity_type":
                            entityType = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "text":
                            text = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "start":
                            start = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "end":
                            end = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!entityType.IsSet)
                throw new ArgumentException("Property is required for class NamedEntityRecognitionResult.", nameof(entityType));

            if (!text.IsSet)
                throw new ArgumentException("Property is required for class NamedEntityRecognitionResult.", nameof(text));

            if (!start.IsSet)
                throw new ArgumentException("Property is required for class NamedEntityRecognitionResult.", nameof(start));

            if (!end.IsSet)
                throw new ArgumentException("Property is required for class NamedEntityRecognitionResult.", nameof(end));

            if (entityType.IsSet && entityType.Value == null)
                throw new ArgumentNullException(nameof(entityType), "Property is not nullable for class NamedEntityRecognitionResult.");

            if (text.IsSet && text.Value == null)
                throw new ArgumentNullException(nameof(text), "Property is not nullable for class NamedEntityRecognitionResult.");

            if (start.IsSet && start.Value == null)
                throw new ArgumentNullException(nameof(start), "Property is not nullable for class NamedEntityRecognitionResult.");

            if (end.IsSet && end.Value == null)
                throw new ArgumentNullException(nameof(end), "Property is not nullable for class NamedEntityRecognitionResult.");

            return new NamedEntityRecognitionResult(entityType.Value!, text.Value!, start.Value!.Value!, end.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="NamedEntityRecognitionResult" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="namedEntityRecognitionResult"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, NamedEntityRecognitionResult namedEntityRecognitionResult, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, namedEntityRecognitionResult, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="NamedEntityRecognitionResult" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="namedEntityRecognitionResult"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, NamedEntityRecognitionResult namedEntityRecognitionResult, JsonSerializerOptions jsonSerializerOptions)
        {
            if (namedEntityRecognitionResult.EntityType == null)
                throw new ArgumentNullException(nameof(namedEntityRecognitionResult.EntityType), "Property is required for class NamedEntityRecognitionResult.");

            if (namedEntityRecognitionResult.Text == null)
                throw new ArgumentNullException(nameof(namedEntityRecognitionResult.Text), "Property is required for class NamedEntityRecognitionResult.");

            writer.WriteString("entity_type", namedEntityRecognitionResult.EntityType);

            writer.WriteString("text", namedEntityRecognitionResult.Text);

            writer.WriteNumber("start", namedEntityRecognitionResult.Start);

            writer.WriteNumber("end", namedEntityRecognitionResult.End);
        }
    }
}
