// <auto-generated>
/*
 * Gladia Control API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Gladia.SDK.Client;

namespace Gladia.SDK.Model
{
    /// <summary>
    /// PayloadTooLargeErrorResponse
    /// </summary>
    public partial class PayloadTooLargeErrorResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PayloadTooLargeErrorResponse" /> class.
        /// </summary>
        /// <param name="timestamp">Date of when the error occurred</param>
        /// <param name="path">Path to the API endpoint</param>
        /// <param name="requestId">Debug id</param>
        /// <param name="statusCode">HTTP status code of the error</param>
        /// <param name="message">Payload too large</param>
        [JsonConstructor]
        public PayloadTooLargeErrorResponse(string timestamp, string path, string requestId, decimal statusCode, string message)
        {
            Timestamp = timestamp;
            Path = path;
            RequestId = requestId;
            StatusCode = statusCode;
            Message = message;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Date of when the error occurred
        /// </summary>
        /// <value>Date of when the error occurred</value>
        /* <example>2023-12-28T09:04:17.210Z</example> */
        [JsonPropertyName("timestamp")]
        public string Timestamp { get; set; }

        /// <summary>
        /// Path to the API endpoint
        /// </summary>
        /// <value>Path to the API endpoint</value>
        /* <example>/v2/transcription/45463597-20b7-4af7-b3b3-f5fb778203ab</example> */
        [JsonPropertyName("path")]
        public string Path { get; set; }

        /// <summary>
        /// Debug id
        /// </summary>
        /// <value>Debug id</value>
        /* <example>G-821fe9df</example> */
        [JsonPropertyName("request_id")]
        public string RequestId { get; set; }

        /// <summary>
        /// HTTP status code of the error
        /// </summary>
        /// <value>HTTP status code of the error</value>
        /* <example>413</example> */
        [JsonPropertyName("statusCode")]
        public decimal StatusCode { get; set; }

        /// <summary>
        /// Payload too large
        /// </summary>
        /// <value>Payload too large</value>
        /* <example>payload too large</example> */
        [JsonPropertyName("message")]
        public string Message { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PayloadTooLargeErrorResponse {\n");
            sb.Append("  Timestamp: ").Append(Timestamp).Append("\n");
            sb.Append("  Path: ").Append(Path).Append("\n");
            sb.Append("  RequestId: ").Append(RequestId).Append("\n");
            sb.Append("  StatusCode: ").Append(StatusCode).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="PayloadTooLargeErrorResponse" />
    /// </summary>
    public class PayloadTooLargeErrorResponseJsonConverter : JsonConverter<PayloadTooLargeErrorResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="PayloadTooLargeErrorResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override PayloadTooLargeErrorResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> timestamp = default;
            Option<string?> path = default;
            Option<string?> requestId = default;
            Option<decimal?> statusCode = default;
            Option<string?> message = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "timestamp":
                            timestamp = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "path":
                            path = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "request_id":
                            requestId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "statusCode":
                            statusCode = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "message":
                            message = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!timestamp.IsSet)
                throw new ArgumentException("Property is required for class PayloadTooLargeErrorResponse.", nameof(timestamp));

            if (!path.IsSet)
                throw new ArgumentException("Property is required for class PayloadTooLargeErrorResponse.", nameof(path));

            if (!requestId.IsSet)
                throw new ArgumentException("Property is required for class PayloadTooLargeErrorResponse.", nameof(requestId));

            if (!statusCode.IsSet)
                throw new ArgumentException("Property is required for class PayloadTooLargeErrorResponse.", nameof(statusCode));

            if (!message.IsSet)
                throw new ArgumentException("Property is required for class PayloadTooLargeErrorResponse.", nameof(message));

            if (timestamp.IsSet && timestamp.Value == null)
                throw new ArgumentNullException(nameof(timestamp), "Property is not nullable for class PayloadTooLargeErrorResponse.");

            if (path.IsSet && path.Value == null)
                throw new ArgumentNullException(nameof(path), "Property is not nullable for class PayloadTooLargeErrorResponse.");

            if (requestId.IsSet && requestId.Value == null)
                throw new ArgumentNullException(nameof(requestId), "Property is not nullable for class PayloadTooLargeErrorResponse.");

            if (statusCode.IsSet && statusCode.Value == null)
                throw new ArgumentNullException(nameof(statusCode), "Property is not nullable for class PayloadTooLargeErrorResponse.");

            if (message.IsSet && message.Value == null)
                throw new ArgumentNullException(nameof(message), "Property is not nullable for class PayloadTooLargeErrorResponse.");

            return new PayloadTooLargeErrorResponse(timestamp.Value!, path.Value!, requestId.Value!, statusCode.Value!.Value!, message.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="PayloadTooLargeErrorResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="payloadTooLargeErrorResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, PayloadTooLargeErrorResponse payloadTooLargeErrorResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, payloadTooLargeErrorResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="PayloadTooLargeErrorResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="payloadTooLargeErrorResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, PayloadTooLargeErrorResponse payloadTooLargeErrorResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (payloadTooLargeErrorResponse.Timestamp == null)
                throw new ArgumentNullException(nameof(payloadTooLargeErrorResponse.Timestamp), "Property is required for class PayloadTooLargeErrorResponse.");

            if (payloadTooLargeErrorResponse.Path == null)
                throw new ArgumentNullException(nameof(payloadTooLargeErrorResponse.Path), "Property is required for class PayloadTooLargeErrorResponse.");

            if (payloadTooLargeErrorResponse.RequestId == null)
                throw new ArgumentNullException(nameof(payloadTooLargeErrorResponse.RequestId), "Property is required for class PayloadTooLargeErrorResponse.");

            if (payloadTooLargeErrorResponse.Message == null)
                throw new ArgumentNullException(nameof(payloadTooLargeErrorResponse.Message), "Property is required for class PayloadTooLargeErrorResponse.");

            writer.WriteString("timestamp", payloadTooLargeErrorResponse.Timestamp);

            writer.WriteString("path", payloadTooLargeErrorResponse.Path);

            writer.WriteString("request_id", payloadTooLargeErrorResponse.RequestId);

            writer.WriteNumber("statusCode", payloadTooLargeErrorResponse.StatusCode);

            writer.WriteString("message", payloadTooLargeErrorResponse.Message);
        }
    }
}
