// <auto-generated>
/*
 * Gladia Control API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Gladia.SDK.Client;

namespace Gladia.SDK.Model
{
    /// <summary>
    /// PostChapterizationMessage
    /// </summary>
    public partial class PostChapterizationMessage : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PostChapterizationMessage" /> class.
        /// </summary>
        /// <param name="sessionId">Id of the live session</param>
        /// <param name="createdAt">Date of creation of the message. The date is formatted as an ISO 8601 string</param>
        /// <param name="error">Error message if the addon failed</param>
        /// <param name="data">The message data. \&quot;null\&quot; if the addon failed</param>
        /// <param name="type">type (default to TypeEnum.PostChapterization)</param>
        [JsonConstructor]
        public PostChapterizationMessage(string sessionId, string createdAt, Error error, PostChapterizationMessageData data, TypeEnum type = TypeEnum.PostChapterization)
        {
            SessionId = sessionId;
            CreatedAt = createdAt;
            Error = error;
            Data = data;
            Type = type;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines Type
        /// </summary>
        public enum TypeEnum
        {
            /// <summary>
            /// Enum PostChapterization for value: post_chapterization
            /// </summary>
            PostChapterization = 1
        }

        /// <summary>
        /// Returns a <see cref="TypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static TypeEnum TypeEnumFromString(string value)
        {
            if (value.Equals("post_chapterization"))
                return TypeEnum.PostChapterization;

            throw new NotImplementedException($"Could not convert value to type TypeEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="TypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static TypeEnum? TypeEnumFromStringOrDefault(string value)
        {
            if (value.Equals("post_chapterization"))
                return TypeEnum.PostChapterization;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="TypeEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string TypeEnumToJsonValue(TypeEnum value)
        {
            if (value == TypeEnum.PostChapterization)
                return "post_chapterization";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        /* <example>post_chapterization</example> */
        [JsonPropertyName("type")]
        public TypeEnum Type { get; set; }

        /// <summary>
        /// Id of the live session
        /// </summary>
        /// <value>Id of the live session</value>
        /* <example>4a39145c-2844-4557-8f34-34883f7be7d9</example> */
        [JsonPropertyName("session_id")]
        public string SessionId { get; set; }

        /// <summary>
        /// Date of creation of the message. The date is formatted as an ISO 8601 string
        /// </summary>
        /// <value>Date of creation of the message. The date is formatted as an ISO 8601 string</value>
        /* <example>2021-09-01T12:00:00.123Z</example> */
        [JsonPropertyName("created_at")]
        public string CreatedAt { get; set; }

        /// <summary>
        /// Error message if the addon failed
        /// </summary>
        /// <value>Error message if the addon failed</value>
        [JsonPropertyName("error")]
        public Error Error { get; set; }

        /// <summary>
        /// The message data. \&quot;null\&quot; if the addon failed
        /// </summary>
        /// <value>The message data. \&quot;null\&quot; if the addon failed</value>
        [JsonPropertyName("data")]
        public PostChapterizationMessageData Data { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PostChapterizationMessage {\n");
            sb.Append("  SessionId: ").Append(SessionId).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  Error: ").Append(Error).Append("\n");
            sb.Append("  Data: ").Append(Data).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="PostChapterizationMessage" />
    /// </summary>
    public class PostChapterizationMessageJsonConverter : JsonConverter<PostChapterizationMessage>
    {
        /// <summary>
        /// Deserializes json to <see cref="PostChapterizationMessage" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override PostChapterizationMessage Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> sessionId = default;
            Option<string?> createdAt = default;
            Option<Error?> error = default;
            Option<PostChapterizationMessageData?> data = default;
            Option<PostChapterizationMessage.TypeEnum?> type = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "session_id":
                            sessionId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "created_at":
                            createdAt = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "error":
                            error = new Option<Error?>(JsonSerializer.Deserialize<Error>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "data":
                            data = new Option<PostChapterizationMessageData?>(JsonSerializer.Deserialize<PostChapterizationMessageData>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "type":
                            string? typeRawValue = utf8JsonReader.GetString();
                            if (typeRawValue != null)
                                type = new Option<PostChapterizationMessage.TypeEnum?>(PostChapterizationMessage.TypeEnumFromStringOrDefault(typeRawValue));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!sessionId.IsSet)
                throw new ArgumentException("Property is required for class PostChapterizationMessage.", nameof(sessionId));

            if (!createdAt.IsSet)
                throw new ArgumentException("Property is required for class PostChapterizationMessage.", nameof(createdAt));

            if (!error.IsSet)
                throw new ArgumentException("Property is required for class PostChapterizationMessage.", nameof(error));

            if (!data.IsSet)
                throw new ArgumentException("Property is required for class PostChapterizationMessage.", nameof(data));

            if (!type.IsSet)
                throw new ArgumentException("Property is required for class PostChapterizationMessage.", nameof(type));

            if (sessionId.IsSet && sessionId.Value == null)
                throw new ArgumentNullException(nameof(sessionId), "Property is not nullable for class PostChapterizationMessage.");

            if (createdAt.IsSet && createdAt.Value == null)
                throw new ArgumentNullException(nameof(createdAt), "Property is not nullable for class PostChapterizationMessage.");

            if (error.IsSet && error.Value == null)
                throw new ArgumentNullException(nameof(error), "Property is not nullable for class PostChapterizationMessage.");

            if (data.IsSet && data.Value == null)
                throw new ArgumentNullException(nameof(data), "Property is not nullable for class PostChapterizationMessage.");

            if (type.IsSet && type.Value == null)
                throw new ArgumentNullException(nameof(type), "Property is not nullable for class PostChapterizationMessage.");

            return new PostChapterizationMessage(sessionId.Value!, createdAt.Value!, error.Value!, data.Value!, type.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="PostChapterizationMessage" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="postChapterizationMessage"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, PostChapterizationMessage postChapterizationMessage, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, postChapterizationMessage, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="PostChapterizationMessage" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="postChapterizationMessage"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, PostChapterizationMessage postChapterizationMessage, JsonSerializerOptions jsonSerializerOptions)
        {
            if (postChapterizationMessage.SessionId == null)
                throw new ArgumentNullException(nameof(postChapterizationMessage.SessionId), "Property is required for class PostChapterizationMessage.");

            if (postChapterizationMessage.CreatedAt == null)
                throw new ArgumentNullException(nameof(postChapterizationMessage.CreatedAt), "Property is required for class PostChapterizationMessage.");

            if (postChapterizationMessage.Error == null)
                throw new ArgumentNullException(nameof(postChapterizationMessage.Error), "Property is required for class PostChapterizationMessage.");

            if (postChapterizationMessage.Data == null)
                throw new ArgumentNullException(nameof(postChapterizationMessage.Data), "Property is required for class PostChapterizationMessage.");

            writer.WriteString("session_id", postChapterizationMessage.SessionId);

            writer.WriteString("created_at", postChapterizationMessage.CreatedAt);

            writer.WritePropertyName("error");
            JsonSerializer.Serialize(writer, postChapterizationMessage.Error, jsonSerializerOptions);
            writer.WritePropertyName("data");
            JsonSerializer.Serialize(writer, postChapterizationMessage.Data, jsonSerializerOptions);
            var typeRawValue = PostChapterizationMessage.TypeEnumToJsonValue(postChapterizationMessage.Type);
            writer.WriteString("type", typeRawValue);
        }
    }
}
