// <auto-generated>
/*
 * Gladia Control API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Gladia.SDK.Client;

namespace Gladia.SDK.Model
{
    /// <summary>
    /// PreProcessingConfig
    /// </summary>
    public partial class PreProcessingConfig : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PreProcessingConfig" /> class.
        /// </summary>
        /// <param name="audioEnhancer">If true, apply pre-processing to the audio stream to enhance the quality. (default to false)</param>
        /// <param name="speechThreshold">Sensitivity configuration for Speech Threshold. A value close to 1 will apply stricter thresholds, making it less likely to detect background sounds as speech. (default to 0.6M)</param>
        [JsonConstructor]
        public PreProcessingConfig(Option<bool?> audioEnhancer = default, Option<decimal?> speechThreshold = default)
        {
            AudioEnhancerOption = audioEnhancer;
            SpeechThresholdOption = speechThreshold;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of AudioEnhancer
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> AudioEnhancerOption { get; private set; }

        /// <summary>
        /// If true, apply pre-processing to the audio stream to enhance the quality.
        /// </summary>
        /// <value>If true, apply pre-processing to the audio stream to enhance the quality.</value>
        [JsonPropertyName("audio_enhancer")]
        public bool? AudioEnhancer { get { return this.AudioEnhancerOption; } set { this.AudioEnhancerOption = new(value); } }

        /// <summary>
        /// Used to track the state of SpeechThreshold
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> SpeechThresholdOption { get; private set; }

        /// <summary>
        /// Sensitivity configuration for Speech Threshold. A value close to 1 will apply stricter thresholds, making it less likely to detect background sounds as speech.
        /// </summary>
        /// <value>Sensitivity configuration for Speech Threshold. A value close to 1 will apply stricter thresholds, making it less likely to detect background sounds as speech.</value>
        [JsonPropertyName("speech_threshold")]
        public decimal? SpeechThreshold { get { return this.SpeechThresholdOption; } set { this.SpeechThresholdOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PreProcessingConfig {\n");
            sb.Append("  AudioEnhancer: ").Append(AudioEnhancer).Append("\n");
            sb.Append("  SpeechThreshold: ").Append(SpeechThreshold).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // SpeechThreshold (decimal) maximum
            if (this.SpeechThresholdOption.IsSet && this.SpeechThresholdOption.Value > (decimal)1)
            {
                yield return new ValidationResult("Invalid value for SpeechThreshold, must be a value less than or equal to 1.", new [] { "SpeechThreshold" });
            }

            // SpeechThreshold (decimal) minimum
            if (this.SpeechThresholdOption.IsSet && this.SpeechThresholdOption.Value < (decimal)0)
            {
                yield return new ValidationResult("Invalid value for SpeechThreshold, must be a value greater than or equal to 0.", new [] { "SpeechThreshold" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="PreProcessingConfig" />
    /// </summary>
    public class PreProcessingConfigJsonConverter : JsonConverter<PreProcessingConfig>
    {
        /// <summary>
        /// Deserializes json to <see cref="PreProcessingConfig" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override PreProcessingConfig Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<bool?> audioEnhancer = default;
            Option<decimal?> speechThreshold = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "audio_enhancer":
                            audioEnhancer = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "speech_threshold":
                            speechThreshold = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (audioEnhancer.IsSet && audioEnhancer.Value == null)
                throw new ArgumentNullException(nameof(audioEnhancer), "Property is not nullable for class PreProcessingConfig.");

            if (speechThreshold.IsSet && speechThreshold.Value == null)
                throw new ArgumentNullException(nameof(speechThreshold), "Property is not nullable for class PreProcessingConfig.");

            return new PreProcessingConfig(audioEnhancer, speechThreshold);
        }

        /// <summary>
        /// Serializes a <see cref="PreProcessingConfig" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="preProcessingConfig"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, PreProcessingConfig preProcessingConfig, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, preProcessingConfig, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="PreProcessingConfig" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="preProcessingConfig"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, PreProcessingConfig preProcessingConfig, JsonSerializerOptions jsonSerializerOptions)
        {
            if (preProcessingConfig.AudioEnhancerOption.IsSet)
                writer.WriteBoolean("audio_enhancer", preProcessingConfig.AudioEnhancerOption.Value!.Value);

            if (preProcessingConfig.SpeechThresholdOption.IsSet)
                writer.WriteNumber("speech_threshold", preProcessingConfig.SpeechThresholdOption.Value!.Value);
        }
    }
}
