// <auto-generated>
/*
 * Gladia Control API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Gladia.SDK.Client;

namespace Gladia.SDK.Model
{
    /// <summary>
    /// PreRecordedRequestParamsResponse
    /// </summary>
    public partial class PreRecordedRequestParamsResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PreRecordedRequestParamsResponse" /> class.
        /// </summary>
        /// <param name="audioUrl">audioUrl</param>
        /// <param name="contextPrompt">**[Deprecated]** Context to feed the transcription model with for possible better accuracy</param>
        /// <param name="customVocabulary">**[Beta]** Can be either boolean to enable custom_vocabulary for this audio or an array with specific vocabulary list to feed the transcription model with (default to false)</param>
        /// <param name="customVocabularyConfig">**[Beta]** Custom vocabulary configuration, if &#x60;custom_vocabulary&#x60; is enabled</param>
        /// <param name="detectLanguage">**[Deprecated]** Use &#x60;language_config&#x60; instead. Detect the language from the given audio (default to true)</param>
        /// <param name="enableCodeSwitching">**[Deprecated]** Use &#x60;language_config&#x60; instead.Detect multiple languages in the given audio (default to false)</param>
        /// <param name="codeSwitchingConfig">**[Deprecated]** Use &#x60;language_config&#x60; instead. Specify the configuration for code switching</param>
        /// <param name="language">**[Deprecated]** Use &#x60;language_config&#x60; instead. Set the spoken language for the given audio (ISO 639 standard)</param>
        /// <param name="callbackUrl">**[Deprecated]** Use &#x60;callback&#x60;/&#x60;callback_config&#x60; instead. Callback URL we will do a &#x60;POST&#x60; request to with the result of the transcription</param>
        /// <param name="callback">Enable callback for this transcription. If true, the &#x60;callback_config&#x60; property will be used to customize the callback behaviour (default to false)</param>
        /// <param name="callbackConfig">Customize the callback behaviour (url and http method)</param>
        /// <param name="subtitles">Enable subtitles generation for this transcription (default to false)</param>
        /// <param name="subtitlesConfig">Configuration for subtitles generation if &#x60;subtitles&#x60; is enabled</param>
        /// <param name="diarization">Enable speaker recognition (diarization) for this audio (default to false)</param>
        /// <param name="diarizationConfig">Speaker recognition configuration, if &#x60;diarization&#x60; is enabled</param>
        /// <param name="translation">**[Beta]** Enable translation for this audio (default to false)</param>
        /// <param name="translationConfig">**[Beta]** Translation configuration, if &#x60;translation&#x60; is enabled</param>
        /// <param name="summarization">**[Beta]** Enable summarization for this audio (default to false)</param>
        /// <param name="summarizationConfig">**[Beta]** Summarization configuration, if &#x60;summarization&#x60; is enabled</param>
        /// <param name="moderation">**[Alpha]** Enable moderation for this audio (default to false)</param>
        /// <param name="namedEntityRecognition">**[Alpha]** Enable named entity recognition for this audio (default to false)</param>
        /// <param name="chapterization">**[Alpha]** Enable chapterization for this audio (default to false)</param>
        /// <param name="nameConsistency">**[Alpha]** Enable names consistency for this audio (default to false)</param>
        /// <param name="customSpelling">**[Alpha]** Enable custom spelling for this audio (default to false)</param>
        /// <param name="customSpellingConfig">**[Alpha]** Custom spelling configuration, if &#x60;custom_spelling&#x60; is enabled</param>
        /// <param name="structuredDataExtraction">**[Alpha]** Enable structured data extraction for this audio (default to false)</param>
        /// <param name="structuredDataExtractionConfig">**[Alpha]** Structured data extraction configuration, if &#x60;structured_data_extraction&#x60; is enabled</param>
        /// <param name="sentimentAnalysis">Enable sentiment analysis for this audio (default to false)</param>
        /// <param name="audioToLlm">**[Alpha]** Enable audio to llm processing for this audio (default to false)</param>
        /// <param name="audioToLlmConfig">**[Alpha]** Audio to llm configuration, if &#x60;audio_to_llm&#x60; is enabled</param>
        /// <param name="sentences">Enable sentences for this audio (default to false)</param>
        /// <param name="displayMode">**[Alpha]** Allows to change the output display_mode for this audio. The output will be reordered, creating new utterances when speakers overlapped (default to false)</param>
        /// <param name="punctuationEnhanced">**[Alpha]** Use enhanced punctuation for this audio (default to false)</param>
        /// <param name="languageConfig">Specify the language configuration</param>
        [JsonConstructor]
        public PreRecordedRequestParamsResponse(string audioUrl, Option<string?> contextPrompt = default, Option<bool?> customVocabulary = default, Option<CustomVocabularyConfigDTO?> customVocabularyConfig = default, Option<bool?> detectLanguage = default, Option<bool?> enableCodeSwitching = default, Option<CodeSwitchingConfigDTO?> codeSwitchingConfig = default, Option<TranscriptionLanguageCodeEnum?> language = default, Option<string?> callbackUrl = default, Option<bool?> callback = default, Option<CallbackConfigDto?> callbackConfig = default, Option<bool?> subtitles = default, Option<SubtitlesConfigDTO?> subtitlesConfig = default, Option<bool?> diarization = default, Option<DiarizationConfigDTO?> diarizationConfig = default, Option<bool?> translation = default, Option<TranslationConfigDTO?> translationConfig = default, Option<bool?> summarization = default, Option<SummarizationConfigDTO?> summarizationConfig = default, Option<bool?> moderation = default, Option<bool?> namedEntityRecognition = default, Option<bool?> chapterization = default, Option<bool?> nameConsistency = default, Option<bool?> customSpelling = default, Option<CustomSpellingConfigDTO?> customSpellingConfig = default, Option<bool?> structuredDataExtraction = default, Option<StructuredDataExtractionConfigDTO?> structuredDataExtractionConfig = default, Option<bool?> sentimentAnalysis = default, Option<bool?> audioToLlm = default, Option<AudioToLlmListConfigDTO?> audioToLlmConfig = default, Option<bool?> sentences = default, Option<bool?> displayMode = default, Option<bool?> punctuationEnhanced = default, Option<LanguageConfig?> languageConfig = default)
        {
            AudioUrl = audioUrl;
            ContextPromptOption = contextPrompt;
            CustomVocabularyOption = customVocabulary;
            CustomVocabularyConfigOption = customVocabularyConfig;
            DetectLanguageOption = detectLanguage;
            EnableCodeSwitchingOption = enableCodeSwitching;
            CodeSwitchingConfigOption = codeSwitchingConfig;
            LanguageOption = language;
            CallbackUrlOption = callbackUrl;
            CallbackOption = callback;
            CallbackConfigOption = callbackConfig;
            SubtitlesOption = subtitles;
            SubtitlesConfigOption = subtitlesConfig;
            DiarizationOption = diarization;
            DiarizationConfigOption = diarizationConfig;
            TranslationOption = translation;
            TranslationConfigOption = translationConfig;
            SummarizationOption = summarization;
            SummarizationConfigOption = summarizationConfig;
            ModerationOption = moderation;
            NamedEntityRecognitionOption = namedEntityRecognition;
            ChapterizationOption = chapterization;
            NameConsistencyOption = nameConsistency;
            CustomSpellingOption = customSpelling;
            CustomSpellingConfigOption = customSpellingConfig;
            StructuredDataExtractionOption = structuredDataExtraction;
            StructuredDataExtractionConfigOption = structuredDataExtractionConfig;
            SentimentAnalysisOption = sentimentAnalysis;
            AudioToLlmOption = audioToLlm;
            AudioToLlmConfigOption = audioToLlmConfig;
            SentencesOption = sentences;
            DisplayModeOption = displayMode;
            PunctuationEnhancedOption = punctuationEnhanced;
            LanguageConfigOption = languageConfig;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Language
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<TranscriptionLanguageCodeEnum?> LanguageOption { get; private set; }

        /// <summary>
        /// **[Deprecated]** Use &#x60;language_config&#x60; instead. Set the spoken language for the given audio (ISO 639 standard)
        /// </summary>
        /// <value>**[Deprecated]** Use &#x60;language_config&#x60; instead. Set the spoken language for the given audio (ISO 639 standard)</value>
        [JsonPropertyName("language")]
        [Obsolete]
        public TranscriptionLanguageCodeEnum? Language { get { return this.LanguageOption; } set { this.LanguageOption = new(value); } }

        /// <summary>
        /// Gets or Sets AudioUrl
        /// </summary>
        [JsonPropertyName("audio_url")]
        public string AudioUrl { get; set; }

        /// <summary>
        /// Used to track the state of ContextPrompt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ContextPromptOption { get; private set; }

        /// <summary>
        /// **[Deprecated]** Context to feed the transcription model with for possible better accuracy
        /// </summary>
        /// <value>**[Deprecated]** Context to feed the transcription model with for possible better accuracy</value>
        [JsonPropertyName("context_prompt")]
        [Obsolete]
        public string? ContextPrompt { get { return this.ContextPromptOption; } set { this.ContextPromptOption = new(value); } }

        /// <summary>
        /// Used to track the state of CustomVocabulary
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> CustomVocabularyOption { get; private set; }

        /// <summary>
        /// **[Beta]** Can be either boolean to enable custom_vocabulary for this audio or an array with specific vocabulary list to feed the transcription model with
        /// </summary>
        /// <value>**[Beta]** Can be either boolean to enable custom_vocabulary for this audio or an array with specific vocabulary list to feed the transcription model with</value>
        [JsonPropertyName("custom_vocabulary")]
        public bool? CustomVocabulary { get { return this.CustomVocabularyOption; } set { this.CustomVocabularyOption = new(value); } }

        /// <summary>
        /// Used to track the state of CustomVocabularyConfig
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<CustomVocabularyConfigDTO?> CustomVocabularyConfigOption { get; private set; }

        /// <summary>
        /// **[Beta]** Custom vocabulary configuration, if &#x60;custom_vocabulary&#x60; is enabled
        /// </summary>
        /// <value>**[Beta]** Custom vocabulary configuration, if &#x60;custom_vocabulary&#x60; is enabled</value>
        [JsonPropertyName("custom_vocabulary_config")]
        public CustomVocabularyConfigDTO? CustomVocabularyConfig { get { return this.CustomVocabularyConfigOption; } set { this.CustomVocabularyConfigOption = new(value); } }

        /// <summary>
        /// Used to track the state of DetectLanguage
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> DetectLanguageOption { get; private set; }

        /// <summary>
        /// **[Deprecated]** Use &#x60;language_config&#x60; instead. Detect the language from the given audio
        /// </summary>
        /// <value>**[Deprecated]** Use &#x60;language_config&#x60; instead. Detect the language from the given audio</value>
        [JsonPropertyName("detect_language")]
        [Obsolete]
        public bool? DetectLanguage { get { return this.DetectLanguageOption; } set { this.DetectLanguageOption = new(value); } }

        /// <summary>
        /// Used to track the state of EnableCodeSwitching
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> EnableCodeSwitchingOption { get; private set; }

        /// <summary>
        /// **[Deprecated]** Use &#x60;language_config&#x60; instead.Detect multiple languages in the given audio
        /// </summary>
        /// <value>**[Deprecated]** Use &#x60;language_config&#x60; instead.Detect multiple languages in the given audio</value>
        [JsonPropertyName("enable_code_switching")]
        [Obsolete]
        public bool? EnableCodeSwitching { get { return this.EnableCodeSwitchingOption; } set { this.EnableCodeSwitchingOption = new(value); } }

        /// <summary>
        /// Used to track the state of CodeSwitchingConfig
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<CodeSwitchingConfigDTO?> CodeSwitchingConfigOption { get; private set; }

        /// <summary>
        /// **[Deprecated]** Use &#x60;language_config&#x60; instead. Specify the configuration for code switching
        /// </summary>
        /// <value>**[Deprecated]** Use &#x60;language_config&#x60; instead. Specify the configuration for code switching</value>
        [JsonPropertyName("code_switching_config")]
        [Obsolete]
        public CodeSwitchingConfigDTO? CodeSwitchingConfig { get { return this.CodeSwitchingConfigOption; } set { this.CodeSwitchingConfigOption = new(value); } }

        /// <summary>
        /// Used to track the state of CallbackUrl
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CallbackUrlOption { get; private set; }

        /// <summary>
        /// **[Deprecated]** Use &#x60;callback&#x60;/&#x60;callback_config&#x60; instead. Callback URL we will do a &#x60;POST&#x60; request to with the result of the transcription
        /// </summary>
        /// <value>**[Deprecated]** Use &#x60;callback&#x60;/&#x60;callback_config&#x60; instead. Callback URL we will do a &#x60;POST&#x60; request to with the result of the transcription</value>
        /* <example>http://callback.example</example> */
        [JsonPropertyName("callback_url")]
        [Obsolete]
        public string? CallbackUrl { get { return this.CallbackUrlOption; } set { this.CallbackUrlOption = new(value); } }

        /// <summary>
        /// Used to track the state of Callback
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> CallbackOption { get; private set; }

        /// <summary>
        /// Enable callback for this transcription. If true, the &#x60;callback_config&#x60; property will be used to customize the callback behaviour
        /// </summary>
        /// <value>Enable callback for this transcription. If true, the &#x60;callback_config&#x60; property will be used to customize the callback behaviour</value>
        [JsonPropertyName("callback")]
        public bool? Callback { get { return this.CallbackOption; } set { this.CallbackOption = new(value); } }

        /// <summary>
        /// Used to track the state of CallbackConfig
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<CallbackConfigDto?> CallbackConfigOption { get; private set; }

        /// <summary>
        /// Customize the callback behaviour (url and http method)
        /// </summary>
        /// <value>Customize the callback behaviour (url and http method)</value>
        [JsonPropertyName("callback_config")]
        public CallbackConfigDto? CallbackConfig { get { return this.CallbackConfigOption; } set { this.CallbackConfigOption = new(value); } }

        /// <summary>
        /// Used to track the state of Subtitles
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> SubtitlesOption { get; private set; }

        /// <summary>
        /// Enable subtitles generation for this transcription
        /// </summary>
        /// <value>Enable subtitles generation for this transcription</value>
        [JsonPropertyName("subtitles")]
        public bool? Subtitles { get { return this.SubtitlesOption; } set { this.SubtitlesOption = new(value); } }

        /// <summary>
        /// Used to track the state of SubtitlesConfig
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<SubtitlesConfigDTO?> SubtitlesConfigOption { get; private set; }

        /// <summary>
        /// Configuration for subtitles generation if &#x60;subtitles&#x60; is enabled
        /// </summary>
        /// <value>Configuration for subtitles generation if &#x60;subtitles&#x60; is enabled</value>
        [JsonPropertyName("subtitles_config")]
        public SubtitlesConfigDTO? SubtitlesConfig { get { return this.SubtitlesConfigOption; } set { this.SubtitlesConfigOption = new(value); } }

        /// <summary>
        /// Used to track the state of Diarization
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> DiarizationOption { get; private set; }

        /// <summary>
        /// Enable speaker recognition (diarization) for this audio
        /// </summary>
        /// <value>Enable speaker recognition (diarization) for this audio</value>
        [JsonPropertyName("diarization")]
        public bool? Diarization { get { return this.DiarizationOption; } set { this.DiarizationOption = new(value); } }

        /// <summary>
        /// Used to track the state of DiarizationConfig
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DiarizationConfigDTO?> DiarizationConfigOption { get; private set; }

        /// <summary>
        /// Speaker recognition configuration, if &#x60;diarization&#x60; is enabled
        /// </summary>
        /// <value>Speaker recognition configuration, if &#x60;diarization&#x60; is enabled</value>
        [JsonPropertyName("diarization_config")]
        public DiarizationConfigDTO? DiarizationConfig { get { return this.DiarizationConfigOption; } set { this.DiarizationConfigOption = new(value); } }

        /// <summary>
        /// Used to track the state of Translation
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> TranslationOption { get; private set; }

        /// <summary>
        /// **[Beta]** Enable translation for this audio
        /// </summary>
        /// <value>**[Beta]** Enable translation for this audio</value>
        [JsonPropertyName("translation")]
        public bool? Translation { get { return this.TranslationOption; } set { this.TranslationOption = new(value); } }

        /// <summary>
        /// Used to track the state of TranslationConfig
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<TranslationConfigDTO?> TranslationConfigOption { get; private set; }

        /// <summary>
        /// **[Beta]** Translation configuration, if &#x60;translation&#x60; is enabled
        /// </summary>
        /// <value>**[Beta]** Translation configuration, if &#x60;translation&#x60; is enabled</value>
        [JsonPropertyName("translation_config")]
        public TranslationConfigDTO? TranslationConfig { get { return this.TranslationConfigOption; } set { this.TranslationConfigOption = new(value); } }

        /// <summary>
        /// Used to track the state of Summarization
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> SummarizationOption { get; private set; }

        /// <summary>
        /// **[Beta]** Enable summarization for this audio
        /// </summary>
        /// <value>**[Beta]** Enable summarization for this audio</value>
        [JsonPropertyName("summarization")]
        public bool? Summarization { get { return this.SummarizationOption; } set { this.SummarizationOption = new(value); } }

        /// <summary>
        /// Used to track the state of SummarizationConfig
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<SummarizationConfigDTO?> SummarizationConfigOption { get; private set; }

        /// <summary>
        /// **[Beta]** Summarization configuration, if &#x60;summarization&#x60; is enabled
        /// </summary>
        /// <value>**[Beta]** Summarization configuration, if &#x60;summarization&#x60; is enabled</value>
        [JsonPropertyName("summarization_config")]
        public SummarizationConfigDTO? SummarizationConfig { get { return this.SummarizationConfigOption; } set { this.SummarizationConfigOption = new(value); } }

        /// <summary>
        /// Used to track the state of Moderation
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> ModerationOption { get; private set; }

        /// <summary>
        /// **[Alpha]** Enable moderation for this audio
        /// </summary>
        /// <value>**[Alpha]** Enable moderation for this audio</value>
        [JsonPropertyName("moderation")]
        public bool? Moderation { get { return this.ModerationOption; } set { this.ModerationOption = new(value); } }

        /// <summary>
        /// Used to track the state of NamedEntityRecognition
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> NamedEntityRecognitionOption { get; private set; }

        /// <summary>
        /// **[Alpha]** Enable named entity recognition for this audio
        /// </summary>
        /// <value>**[Alpha]** Enable named entity recognition for this audio</value>
        [JsonPropertyName("named_entity_recognition")]
        public bool? NamedEntityRecognition { get { return this.NamedEntityRecognitionOption; } set { this.NamedEntityRecognitionOption = new(value); } }

        /// <summary>
        /// Used to track the state of Chapterization
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> ChapterizationOption { get; private set; }

        /// <summary>
        /// **[Alpha]** Enable chapterization for this audio
        /// </summary>
        /// <value>**[Alpha]** Enable chapterization for this audio</value>
        [JsonPropertyName("chapterization")]
        public bool? Chapterization { get { return this.ChapterizationOption; } set { this.ChapterizationOption = new(value); } }

        /// <summary>
        /// Used to track the state of NameConsistency
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> NameConsistencyOption { get; private set; }

        /// <summary>
        /// **[Alpha]** Enable names consistency for this audio
        /// </summary>
        /// <value>**[Alpha]** Enable names consistency for this audio</value>
        [JsonPropertyName("name_consistency")]
        public bool? NameConsistency { get { return this.NameConsistencyOption; } set { this.NameConsistencyOption = new(value); } }

        /// <summary>
        /// Used to track the state of CustomSpelling
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> CustomSpellingOption { get; private set; }

        /// <summary>
        /// **[Alpha]** Enable custom spelling for this audio
        /// </summary>
        /// <value>**[Alpha]** Enable custom spelling for this audio</value>
        [JsonPropertyName("custom_spelling")]
        public bool? CustomSpelling { get { return this.CustomSpellingOption; } set { this.CustomSpellingOption = new(value); } }

        /// <summary>
        /// Used to track the state of CustomSpellingConfig
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<CustomSpellingConfigDTO?> CustomSpellingConfigOption { get; private set; }

        /// <summary>
        /// **[Alpha]** Custom spelling configuration, if &#x60;custom_spelling&#x60; is enabled
        /// </summary>
        /// <value>**[Alpha]** Custom spelling configuration, if &#x60;custom_spelling&#x60; is enabled</value>
        [JsonPropertyName("custom_spelling_config")]
        public CustomSpellingConfigDTO? CustomSpellingConfig { get { return this.CustomSpellingConfigOption; } set { this.CustomSpellingConfigOption = new(value); } }

        /// <summary>
        /// Used to track the state of StructuredDataExtraction
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> StructuredDataExtractionOption { get; private set; }

        /// <summary>
        /// **[Alpha]** Enable structured data extraction for this audio
        /// </summary>
        /// <value>**[Alpha]** Enable structured data extraction for this audio</value>
        [JsonPropertyName("structured_data_extraction")]
        public bool? StructuredDataExtraction { get { return this.StructuredDataExtractionOption; } set { this.StructuredDataExtractionOption = new(value); } }

        /// <summary>
        /// Used to track the state of StructuredDataExtractionConfig
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<StructuredDataExtractionConfigDTO?> StructuredDataExtractionConfigOption { get; private set; }

        /// <summary>
        /// **[Alpha]** Structured data extraction configuration, if &#x60;structured_data_extraction&#x60; is enabled
        /// </summary>
        /// <value>**[Alpha]** Structured data extraction configuration, if &#x60;structured_data_extraction&#x60; is enabled</value>
        [JsonPropertyName("structured_data_extraction_config")]
        public StructuredDataExtractionConfigDTO? StructuredDataExtractionConfig { get { return this.StructuredDataExtractionConfigOption; } set { this.StructuredDataExtractionConfigOption = new(value); } }

        /// <summary>
        /// Used to track the state of SentimentAnalysis
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> SentimentAnalysisOption { get; private set; }

        /// <summary>
        /// Enable sentiment analysis for this audio
        /// </summary>
        /// <value>Enable sentiment analysis for this audio</value>
        [JsonPropertyName("sentiment_analysis")]
        public bool? SentimentAnalysis { get { return this.SentimentAnalysisOption; } set { this.SentimentAnalysisOption = new(value); } }

        /// <summary>
        /// Used to track the state of AudioToLlm
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> AudioToLlmOption { get; private set; }

        /// <summary>
        /// **[Alpha]** Enable audio to llm processing for this audio
        /// </summary>
        /// <value>**[Alpha]** Enable audio to llm processing for this audio</value>
        [JsonPropertyName("audio_to_llm")]
        public bool? AudioToLlm { get { return this.AudioToLlmOption; } set { this.AudioToLlmOption = new(value); } }

        /// <summary>
        /// Used to track the state of AudioToLlmConfig
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<AudioToLlmListConfigDTO?> AudioToLlmConfigOption { get; private set; }

        /// <summary>
        /// **[Alpha]** Audio to llm configuration, if &#x60;audio_to_llm&#x60; is enabled
        /// </summary>
        /// <value>**[Alpha]** Audio to llm configuration, if &#x60;audio_to_llm&#x60; is enabled</value>
        [JsonPropertyName("audio_to_llm_config")]
        public AudioToLlmListConfigDTO? AudioToLlmConfig { get { return this.AudioToLlmConfigOption; } set { this.AudioToLlmConfigOption = new(value); } }

        /// <summary>
        /// Used to track the state of Sentences
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> SentencesOption { get; private set; }

        /// <summary>
        /// Enable sentences for this audio
        /// </summary>
        /// <value>Enable sentences for this audio</value>
        [JsonPropertyName("sentences")]
        public bool? Sentences { get { return this.SentencesOption; } set { this.SentencesOption = new(value); } }

        /// <summary>
        /// Used to track the state of DisplayMode
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> DisplayModeOption { get; private set; }

        /// <summary>
        /// **[Alpha]** Allows to change the output display_mode for this audio. The output will be reordered, creating new utterances when speakers overlapped
        /// </summary>
        /// <value>**[Alpha]** Allows to change the output display_mode for this audio. The output will be reordered, creating new utterances when speakers overlapped</value>
        [JsonPropertyName("display_mode")]
        public bool? DisplayMode { get { return this.DisplayModeOption; } set { this.DisplayModeOption = new(value); } }

        /// <summary>
        /// Used to track the state of PunctuationEnhanced
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> PunctuationEnhancedOption { get; private set; }

        /// <summary>
        /// **[Alpha]** Use enhanced punctuation for this audio
        /// </summary>
        /// <value>**[Alpha]** Use enhanced punctuation for this audio</value>
        [JsonPropertyName("punctuation_enhanced")]
        public bool? PunctuationEnhanced { get { return this.PunctuationEnhancedOption; } set { this.PunctuationEnhancedOption = new(value); } }

        /// <summary>
        /// Used to track the state of LanguageConfig
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<LanguageConfig?> LanguageConfigOption { get; private set; }

        /// <summary>
        /// Specify the language configuration
        /// </summary>
        /// <value>Specify the language configuration</value>
        [JsonPropertyName("language_config")]
        public LanguageConfig? LanguageConfig { get { return this.LanguageConfigOption; } set { this.LanguageConfigOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PreRecordedRequestParamsResponse {\n");
            sb.Append("  AudioUrl: ").Append(AudioUrl).Append("\n");
            sb.Append("  ContextPrompt: ").Append(ContextPrompt).Append("\n");
            sb.Append("  CustomVocabulary: ").Append(CustomVocabulary).Append("\n");
            sb.Append("  CustomVocabularyConfig: ").Append(CustomVocabularyConfig).Append("\n");
            sb.Append("  DetectLanguage: ").Append(DetectLanguage).Append("\n");
            sb.Append("  EnableCodeSwitching: ").Append(EnableCodeSwitching).Append("\n");
            sb.Append("  CodeSwitchingConfig: ").Append(CodeSwitchingConfig).Append("\n");
            sb.Append("  Language: ").Append(Language).Append("\n");
            sb.Append("  CallbackUrl: ").Append(CallbackUrl).Append("\n");
            sb.Append("  Callback: ").Append(Callback).Append("\n");
            sb.Append("  CallbackConfig: ").Append(CallbackConfig).Append("\n");
            sb.Append("  Subtitles: ").Append(Subtitles).Append("\n");
            sb.Append("  SubtitlesConfig: ").Append(SubtitlesConfig).Append("\n");
            sb.Append("  Diarization: ").Append(Diarization).Append("\n");
            sb.Append("  DiarizationConfig: ").Append(DiarizationConfig).Append("\n");
            sb.Append("  Translation: ").Append(Translation).Append("\n");
            sb.Append("  TranslationConfig: ").Append(TranslationConfig).Append("\n");
            sb.Append("  Summarization: ").Append(Summarization).Append("\n");
            sb.Append("  SummarizationConfig: ").Append(SummarizationConfig).Append("\n");
            sb.Append("  Moderation: ").Append(Moderation).Append("\n");
            sb.Append("  NamedEntityRecognition: ").Append(NamedEntityRecognition).Append("\n");
            sb.Append("  Chapterization: ").Append(Chapterization).Append("\n");
            sb.Append("  NameConsistency: ").Append(NameConsistency).Append("\n");
            sb.Append("  CustomSpelling: ").Append(CustomSpelling).Append("\n");
            sb.Append("  CustomSpellingConfig: ").Append(CustomSpellingConfig).Append("\n");
            sb.Append("  StructuredDataExtraction: ").Append(StructuredDataExtraction).Append("\n");
            sb.Append("  StructuredDataExtractionConfig: ").Append(StructuredDataExtractionConfig).Append("\n");
            sb.Append("  SentimentAnalysis: ").Append(SentimentAnalysis).Append("\n");
            sb.Append("  AudioToLlm: ").Append(AudioToLlm).Append("\n");
            sb.Append("  AudioToLlmConfig: ").Append(AudioToLlmConfig).Append("\n");
            sb.Append("  Sentences: ").Append(Sentences).Append("\n");
            sb.Append("  DisplayMode: ").Append(DisplayMode).Append("\n");
            sb.Append("  PunctuationEnhanced: ").Append(PunctuationEnhanced).Append("\n");
            sb.Append("  LanguageConfig: ").Append(LanguageConfig).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="PreRecordedRequestParamsResponse" />
    /// </summary>
    public class PreRecordedRequestParamsResponseJsonConverter : JsonConverter<PreRecordedRequestParamsResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="PreRecordedRequestParamsResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override PreRecordedRequestParamsResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> audioUrl = default;
            Option<string?> contextPrompt = default;
            Option<bool?> customVocabulary = default;
            Option<CustomVocabularyConfigDTO?> customVocabularyConfig = default;
            Option<bool?> detectLanguage = default;
            Option<bool?> enableCodeSwitching = default;
            Option<CodeSwitchingConfigDTO?> codeSwitchingConfig = default;
            Option<TranscriptionLanguageCodeEnum?> language = default;
            Option<string?> callbackUrl = default;
            Option<bool?> callback = default;
            Option<CallbackConfigDto?> callbackConfig = default;
            Option<bool?> subtitles = default;
            Option<SubtitlesConfigDTO?> subtitlesConfig = default;
            Option<bool?> diarization = default;
            Option<DiarizationConfigDTO?> diarizationConfig = default;
            Option<bool?> translation = default;
            Option<TranslationConfigDTO?> translationConfig = default;
            Option<bool?> summarization = default;
            Option<SummarizationConfigDTO?> summarizationConfig = default;
            Option<bool?> moderation = default;
            Option<bool?> namedEntityRecognition = default;
            Option<bool?> chapterization = default;
            Option<bool?> nameConsistency = default;
            Option<bool?> customSpelling = default;
            Option<CustomSpellingConfigDTO?> customSpellingConfig = default;
            Option<bool?> structuredDataExtraction = default;
            Option<StructuredDataExtractionConfigDTO?> structuredDataExtractionConfig = default;
            Option<bool?> sentimentAnalysis = default;
            Option<bool?> audioToLlm = default;
            Option<AudioToLlmListConfigDTO?> audioToLlmConfig = default;
            Option<bool?> sentences = default;
            Option<bool?> displayMode = default;
            Option<bool?> punctuationEnhanced = default;
            Option<LanguageConfig?> languageConfig = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "audio_url":
                            audioUrl = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "context_prompt":
                            contextPrompt = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "custom_vocabulary":
                            customVocabulary = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "custom_vocabulary_config":
                            customVocabularyConfig = new Option<CustomVocabularyConfigDTO?>(JsonSerializer.Deserialize<CustomVocabularyConfigDTO>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "detect_language":
                            detectLanguage = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "enable_code_switching":
                            enableCodeSwitching = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "code_switching_config":
                            codeSwitchingConfig = new Option<CodeSwitchingConfigDTO?>(JsonSerializer.Deserialize<CodeSwitchingConfigDTO>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "language":
                            string? languageRawValue = utf8JsonReader.GetString();
                            if (languageRawValue != null)
                                language = new Option<TranscriptionLanguageCodeEnum?>(TranscriptionLanguageCodeEnumValueConverter.FromStringOrDefault(languageRawValue));
                            break;
                        case "callback_url":
                            callbackUrl = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "callback":
                            callback = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "callback_config":
                            callbackConfig = new Option<CallbackConfigDto?>(JsonSerializer.Deserialize<CallbackConfigDto>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "subtitles":
                            subtitles = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "subtitles_config":
                            subtitlesConfig = new Option<SubtitlesConfigDTO?>(JsonSerializer.Deserialize<SubtitlesConfigDTO>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "diarization":
                            diarization = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "diarization_config":
                            diarizationConfig = new Option<DiarizationConfigDTO?>(JsonSerializer.Deserialize<DiarizationConfigDTO>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "translation":
                            translation = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "translation_config":
                            translationConfig = new Option<TranslationConfigDTO?>(JsonSerializer.Deserialize<TranslationConfigDTO>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "summarization":
                            summarization = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "summarization_config":
                            summarizationConfig = new Option<SummarizationConfigDTO?>(JsonSerializer.Deserialize<SummarizationConfigDTO>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "moderation":
                            moderation = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "named_entity_recognition":
                            namedEntityRecognition = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "chapterization":
                            chapterization = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "name_consistency":
                            nameConsistency = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "custom_spelling":
                            customSpelling = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "custom_spelling_config":
                            customSpellingConfig = new Option<CustomSpellingConfigDTO?>(JsonSerializer.Deserialize<CustomSpellingConfigDTO>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "structured_data_extraction":
                            structuredDataExtraction = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "structured_data_extraction_config":
                            structuredDataExtractionConfig = new Option<StructuredDataExtractionConfigDTO?>(JsonSerializer.Deserialize<StructuredDataExtractionConfigDTO>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "sentiment_analysis":
                            sentimentAnalysis = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "audio_to_llm":
                            audioToLlm = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "audio_to_llm_config":
                            audioToLlmConfig = new Option<AudioToLlmListConfigDTO?>(JsonSerializer.Deserialize<AudioToLlmListConfigDTO>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "sentences":
                            sentences = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "display_mode":
                            displayMode = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "punctuation_enhanced":
                            punctuationEnhanced = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "language_config":
                            languageConfig = new Option<LanguageConfig?>(JsonSerializer.Deserialize<LanguageConfig>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!audioUrl.IsSet)
                throw new ArgumentException("Property is required for class PreRecordedRequestParamsResponse.", nameof(audioUrl));

            if (audioUrl.IsSet && audioUrl.Value == null)
                throw new ArgumentNullException(nameof(audioUrl), "Property is not nullable for class PreRecordedRequestParamsResponse.");

            if (contextPrompt.IsSet && contextPrompt.Value == null)
                throw new ArgumentNullException(nameof(contextPrompt), "Property is not nullable for class PreRecordedRequestParamsResponse.");

            if (customVocabulary.IsSet && customVocabulary.Value == null)
                throw new ArgumentNullException(nameof(customVocabulary), "Property is not nullable for class PreRecordedRequestParamsResponse.");

            if (customVocabularyConfig.IsSet && customVocabularyConfig.Value == null)
                throw new ArgumentNullException(nameof(customVocabularyConfig), "Property is not nullable for class PreRecordedRequestParamsResponse.");

            if (detectLanguage.IsSet && detectLanguage.Value == null)
                throw new ArgumentNullException(nameof(detectLanguage), "Property is not nullable for class PreRecordedRequestParamsResponse.");

            if (enableCodeSwitching.IsSet && enableCodeSwitching.Value == null)
                throw new ArgumentNullException(nameof(enableCodeSwitching), "Property is not nullable for class PreRecordedRequestParamsResponse.");

            if (codeSwitchingConfig.IsSet && codeSwitchingConfig.Value == null)
                throw new ArgumentNullException(nameof(codeSwitchingConfig), "Property is not nullable for class PreRecordedRequestParamsResponse.");

            if (language.IsSet && language.Value == null)
                throw new ArgumentNullException(nameof(language), "Property is not nullable for class PreRecordedRequestParamsResponse.");

            if (callbackUrl.IsSet && callbackUrl.Value == null)
                throw new ArgumentNullException(nameof(callbackUrl), "Property is not nullable for class PreRecordedRequestParamsResponse.");

            if (callback.IsSet && callback.Value == null)
                throw new ArgumentNullException(nameof(callback), "Property is not nullable for class PreRecordedRequestParamsResponse.");

            if (callbackConfig.IsSet && callbackConfig.Value == null)
                throw new ArgumentNullException(nameof(callbackConfig), "Property is not nullable for class PreRecordedRequestParamsResponse.");

            if (subtitles.IsSet && subtitles.Value == null)
                throw new ArgumentNullException(nameof(subtitles), "Property is not nullable for class PreRecordedRequestParamsResponse.");

            if (subtitlesConfig.IsSet && subtitlesConfig.Value == null)
                throw new ArgumentNullException(nameof(subtitlesConfig), "Property is not nullable for class PreRecordedRequestParamsResponse.");

            if (diarization.IsSet && diarization.Value == null)
                throw new ArgumentNullException(nameof(diarization), "Property is not nullable for class PreRecordedRequestParamsResponse.");

            if (diarizationConfig.IsSet && diarizationConfig.Value == null)
                throw new ArgumentNullException(nameof(diarizationConfig), "Property is not nullable for class PreRecordedRequestParamsResponse.");

            if (translation.IsSet && translation.Value == null)
                throw new ArgumentNullException(nameof(translation), "Property is not nullable for class PreRecordedRequestParamsResponse.");

            if (translationConfig.IsSet && translationConfig.Value == null)
                throw new ArgumentNullException(nameof(translationConfig), "Property is not nullable for class PreRecordedRequestParamsResponse.");

            if (summarization.IsSet && summarization.Value == null)
                throw new ArgumentNullException(nameof(summarization), "Property is not nullable for class PreRecordedRequestParamsResponse.");

            if (summarizationConfig.IsSet && summarizationConfig.Value == null)
                throw new ArgumentNullException(nameof(summarizationConfig), "Property is not nullable for class PreRecordedRequestParamsResponse.");

            if (moderation.IsSet && moderation.Value == null)
                throw new ArgumentNullException(nameof(moderation), "Property is not nullable for class PreRecordedRequestParamsResponse.");

            if (namedEntityRecognition.IsSet && namedEntityRecognition.Value == null)
                throw new ArgumentNullException(nameof(namedEntityRecognition), "Property is not nullable for class PreRecordedRequestParamsResponse.");

            if (chapterization.IsSet && chapterization.Value == null)
                throw new ArgumentNullException(nameof(chapterization), "Property is not nullable for class PreRecordedRequestParamsResponse.");

            if (nameConsistency.IsSet && nameConsistency.Value == null)
                throw new ArgumentNullException(nameof(nameConsistency), "Property is not nullable for class PreRecordedRequestParamsResponse.");

            if (customSpelling.IsSet && customSpelling.Value == null)
                throw new ArgumentNullException(nameof(customSpelling), "Property is not nullable for class PreRecordedRequestParamsResponse.");

            if (customSpellingConfig.IsSet && customSpellingConfig.Value == null)
                throw new ArgumentNullException(nameof(customSpellingConfig), "Property is not nullable for class PreRecordedRequestParamsResponse.");

            if (structuredDataExtraction.IsSet && structuredDataExtraction.Value == null)
                throw new ArgumentNullException(nameof(structuredDataExtraction), "Property is not nullable for class PreRecordedRequestParamsResponse.");

            if (structuredDataExtractionConfig.IsSet && structuredDataExtractionConfig.Value == null)
                throw new ArgumentNullException(nameof(structuredDataExtractionConfig), "Property is not nullable for class PreRecordedRequestParamsResponse.");

            if (sentimentAnalysis.IsSet && sentimentAnalysis.Value == null)
                throw new ArgumentNullException(nameof(sentimentAnalysis), "Property is not nullable for class PreRecordedRequestParamsResponse.");

            if (audioToLlm.IsSet && audioToLlm.Value == null)
                throw new ArgumentNullException(nameof(audioToLlm), "Property is not nullable for class PreRecordedRequestParamsResponse.");

            if (audioToLlmConfig.IsSet && audioToLlmConfig.Value == null)
                throw new ArgumentNullException(nameof(audioToLlmConfig), "Property is not nullable for class PreRecordedRequestParamsResponse.");

            if (sentences.IsSet && sentences.Value == null)
                throw new ArgumentNullException(nameof(sentences), "Property is not nullable for class PreRecordedRequestParamsResponse.");

            if (displayMode.IsSet && displayMode.Value == null)
                throw new ArgumentNullException(nameof(displayMode), "Property is not nullable for class PreRecordedRequestParamsResponse.");

            if (punctuationEnhanced.IsSet && punctuationEnhanced.Value == null)
                throw new ArgumentNullException(nameof(punctuationEnhanced), "Property is not nullable for class PreRecordedRequestParamsResponse.");

            if (languageConfig.IsSet && languageConfig.Value == null)
                throw new ArgumentNullException(nameof(languageConfig), "Property is not nullable for class PreRecordedRequestParamsResponse.");

            return new PreRecordedRequestParamsResponse(audioUrl.Value!, contextPrompt, customVocabulary, customVocabularyConfig, detectLanguage, enableCodeSwitching, codeSwitchingConfig, language, callbackUrl, callback, callbackConfig, subtitles, subtitlesConfig, diarization, diarizationConfig, translation, translationConfig, summarization, summarizationConfig, moderation, namedEntityRecognition, chapterization, nameConsistency, customSpelling, customSpellingConfig, structuredDataExtraction, structuredDataExtractionConfig, sentimentAnalysis, audioToLlm, audioToLlmConfig, sentences, displayMode, punctuationEnhanced, languageConfig);
        }

        /// <summary>
        /// Serializes a <see cref="PreRecordedRequestParamsResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="preRecordedRequestParamsResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, PreRecordedRequestParamsResponse preRecordedRequestParamsResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, preRecordedRequestParamsResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="PreRecordedRequestParamsResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="preRecordedRequestParamsResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, PreRecordedRequestParamsResponse preRecordedRequestParamsResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (preRecordedRequestParamsResponse.AudioUrl == null)
                throw new ArgumentNullException(nameof(preRecordedRequestParamsResponse.AudioUrl), "Property is required for class PreRecordedRequestParamsResponse.");

            if (preRecordedRequestParamsResponse.ContextPromptOption.IsSet && preRecordedRequestParamsResponse.ContextPrompt == null)
                throw new ArgumentNullException(nameof(preRecordedRequestParamsResponse.ContextPrompt), "Property is required for class PreRecordedRequestParamsResponse.");

            if (preRecordedRequestParamsResponse.CustomVocabularyConfigOption.IsSet && preRecordedRequestParamsResponse.CustomVocabularyConfig == null)
                throw new ArgumentNullException(nameof(preRecordedRequestParamsResponse.CustomVocabularyConfig), "Property is required for class PreRecordedRequestParamsResponse.");

            if (preRecordedRequestParamsResponse.CodeSwitchingConfigOption.IsSet && preRecordedRequestParamsResponse.CodeSwitchingConfig == null)
                throw new ArgumentNullException(nameof(preRecordedRequestParamsResponse.CodeSwitchingConfig), "Property is required for class PreRecordedRequestParamsResponse.");

            if (preRecordedRequestParamsResponse.CallbackUrlOption.IsSet && preRecordedRequestParamsResponse.CallbackUrl == null)
                throw new ArgumentNullException(nameof(preRecordedRequestParamsResponse.CallbackUrl), "Property is required for class PreRecordedRequestParamsResponse.");

            if (preRecordedRequestParamsResponse.CallbackConfigOption.IsSet && preRecordedRequestParamsResponse.CallbackConfig == null)
                throw new ArgumentNullException(nameof(preRecordedRequestParamsResponse.CallbackConfig), "Property is required for class PreRecordedRequestParamsResponse.");

            if (preRecordedRequestParamsResponse.SubtitlesConfigOption.IsSet && preRecordedRequestParamsResponse.SubtitlesConfig == null)
                throw new ArgumentNullException(nameof(preRecordedRequestParamsResponse.SubtitlesConfig), "Property is required for class PreRecordedRequestParamsResponse.");

            if (preRecordedRequestParamsResponse.DiarizationConfigOption.IsSet && preRecordedRequestParamsResponse.DiarizationConfig == null)
                throw new ArgumentNullException(nameof(preRecordedRequestParamsResponse.DiarizationConfig), "Property is required for class PreRecordedRequestParamsResponse.");

            if (preRecordedRequestParamsResponse.TranslationConfigOption.IsSet && preRecordedRequestParamsResponse.TranslationConfig == null)
                throw new ArgumentNullException(nameof(preRecordedRequestParamsResponse.TranslationConfig), "Property is required for class PreRecordedRequestParamsResponse.");

            if (preRecordedRequestParamsResponse.SummarizationConfigOption.IsSet && preRecordedRequestParamsResponse.SummarizationConfig == null)
                throw new ArgumentNullException(nameof(preRecordedRequestParamsResponse.SummarizationConfig), "Property is required for class PreRecordedRequestParamsResponse.");

            if (preRecordedRequestParamsResponse.CustomSpellingConfigOption.IsSet && preRecordedRequestParamsResponse.CustomSpellingConfig == null)
                throw new ArgumentNullException(nameof(preRecordedRequestParamsResponse.CustomSpellingConfig), "Property is required for class PreRecordedRequestParamsResponse.");

            if (preRecordedRequestParamsResponse.StructuredDataExtractionConfigOption.IsSet && preRecordedRequestParamsResponse.StructuredDataExtractionConfig == null)
                throw new ArgumentNullException(nameof(preRecordedRequestParamsResponse.StructuredDataExtractionConfig), "Property is required for class PreRecordedRequestParamsResponse.");

            if (preRecordedRequestParamsResponse.AudioToLlmConfigOption.IsSet && preRecordedRequestParamsResponse.AudioToLlmConfig == null)
                throw new ArgumentNullException(nameof(preRecordedRequestParamsResponse.AudioToLlmConfig), "Property is required for class PreRecordedRequestParamsResponse.");

            if (preRecordedRequestParamsResponse.LanguageConfigOption.IsSet && preRecordedRequestParamsResponse.LanguageConfig == null)
                throw new ArgumentNullException(nameof(preRecordedRequestParamsResponse.LanguageConfig), "Property is required for class PreRecordedRequestParamsResponse.");

            writer.WriteString("audio_url", preRecordedRequestParamsResponse.AudioUrl);

            if (preRecordedRequestParamsResponse.ContextPromptOption.IsSet)
                writer.WriteString("context_prompt", preRecordedRequestParamsResponse.ContextPrompt);

            if (preRecordedRequestParamsResponse.CustomVocabularyOption.IsSet)
                writer.WriteBoolean("custom_vocabulary", preRecordedRequestParamsResponse.CustomVocabularyOption.Value!.Value);

            if (preRecordedRequestParamsResponse.CustomVocabularyConfigOption.IsSet)
            {
                writer.WritePropertyName("custom_vocabulary_config");
                JsonSerializer.Serialize(writer, preRecordedRequestParamsResponse.CustomVocabularyConfig, jsonSerializerOptions);
            }
            if (preRecordedRequestParamsResponse.DetectLanguageOption.IsSet)
                writer.WriteBoolean("detect_language", preRecordedRequestParamsResponse.DetectLanguageOption.Value!.Value);

            if (preRecordedRequestParamsResponse.EnableCodeSwitchingOption.IsSet)
                writer.WriteBoolean("enable_code_switching", preRecordedRequestParamsResponse.EnableCodeSwitchingOption.Value!.Value);

            if (preRecordedRequestParamsResponse.CodeSwitchingConfigOption.IsSet)
            {
                writer.WritePropertyName("code_switching_config");
                JsonSerializer.Serialize(writer, preRecordedRequestParamsResponse.CodeSwitchingConfig, jsonSerializerOptions);
            }
            if (preRecordedRequestParamsResponse.LanguageOption.IsSet)
            {
                var languageRawValue = TranscriptionLanguageCodeEnumValueConverter.ToJsonValue(preRecordedRequestParamsResponse.Language!.Value);
                writer.WriteString("language", languageRawValue);
            }
            if (preRecordedRequestParamsResponse.CallbackUrlOption.IsSet)
                writer.WriteString("callback_url", preRecordedRequestParamsResponse.CallbackUrl);

            if (preRecordedRequestParamsResponse.CallbackOption.IsSet)
                writer.WriteBoolean("callback", preRecordedRequestParamsResponse.CallbackOption.Value!.Value);

            if (preRecordedRequestParamsResponse.CallbackConfigOption.IsSet)
            {
                writer.WritePropertyName("callback_config");
                JsonSerializer.Serialize(writer, preRecordedRequestParamsResponse.CallbackConfig, jsonSerializerOptions);
            }
            if (preRecordedRequestParamsResponse.SubtitlesOption.IsSet)
                writer.WriteBoolean("subtitles", preRecordedRequestParamsResponse.SubtitlesOption.Value!.Value);

            if (preRecordedRequestParamsResponse.SubtitlesConfigOption.IsSet)
            {
                writer.WritePropertyName("subtitles_config");
                JsonSerializer.Serialize(writer, preRecordedRequestParamsResponse.SubtitlesConfig, jsonSerializerOptions);
            }
            if (preRecordedRequestParamsResponse.DiarizationOption.IsSet)
                writer.WriteBoolean("diarization", preRecordedRequestParamsResponse.DiarizationOption.Value!.Value);

            if (preRecordedRequestParamsResponse.DiarizationConfigOption.IsSet)
            {
                writer.WritePropertyName("diarization_config");
                JsonSerializer.Serialize(writer, preRecordedRequestParamsResponse.DiarizationConfig, jsonSerializerOptions);
            }
            if (preRecordedRequestParamsResponse.TranslationOption.IsSet)
                writer.WriteBoolean("translation", preRecordedRequestParamsResponse.TranslationOption.Value!.Value);

            if (preRecordedRequestParamsResponse.TranslationConfigOption.IsSet)
            {
                writer.WritePropertyName("translation_config");
                JsonSerializer.Serialize(writer, preRecordedRequestParamsResponse.TranslationConfig, jsonSerializerOptions);
            }
            if (preRecordedRequestParamsResponse.SummarizationOption.IsSet)
                writer.WriteBoolean("summarization", preRecordedRequestParamsResponse.SummarizationOption.Value!.Value);

            if (preRecordedRequestParamsResponse.SummarizationConfigOption.IsSet)
            {
                writer.WritePropertyName("summarization_config");
                JsonSerializer.Serialize(writer, preRecordedRequestParamsResponse.SummarizationConfig, jsonSerializerOptions);
            }
            if (preRecordedRequestParamsResponse.ModerationOption.IsSet)
                writer.WriteBoolean("moderation", preRecordedRequestParamsResponse.ModerationOption.Value!.Value);

            if (preRecordedRequestParamsResponse.NamedEntityRecognitionOption.IsSet)
                writer.WriteBoolean("named_entity_recognition", preRecordedRequestParamsResponse.NamedEntityRecognitionOption.Value!.Value);

            if (preRecordedRequestParamsResponse.ChapterizationOption.IsSet)
                writer.WriteBoolean("chapterization", preRecordedRequestParamsResponse.ChapterizationOption.Value!.Value);

            if (preRecordedRequestParamsResponse.NameConsistencyOption.IsSet)
                writer.WriteBoolean("name_consistency", preRecordedRequestParamsResponse.NameConsistencyOption.Value!.Value);

            if (preRecordedRequestParamsResponse.CustomSpellingOption.IsSet)
                writer.WriteBoolean("custom_spelling", preRecordedRequestParamsResponse.CustomSpellingOption.Value!.Value);

            if (preRecordedRequestParamsResponse.CustomSpellingConfigOption.IsSet)
            {
                writer.WritePropertyName("custom_spelling_config");
                JsonSerializer.Serialize(writer, preRecordedRequestParamsResponse.CustomSpellingConfig, jsonSerializerOptions);
            }
            if (preRecordedRequestParamsResponse.StructuredDataExtractionOption.IsSet)
                writer.WriteBoolean("structured_data_extraction", preRecordedRequestParamsResponse.StructuredDataExtractionOption.Value!.Value);

            if (preRecordedRequestParamsResponse.StructuredDataExtractionConfigOption.IsSet)
            {
                writer.WritePropertyName("structured_data_extraction_config");
                JsonSerializer.Serialize(writer, preRecordedRequestParamsResponse.StructuredDataExtractionConfig, jsonSerializerOptions);
            }
            if (preRecordedRequestParamsResponse.SentimentAnalysisOption.IsSet)
                writer.WriteBoolean("sentiment_analysis", preRecordedRequestParamsResponse.SentimentAnalysisOption.Value!.Value);

            if (preRecordedRequestParamsResponse.AudioToLlmOption.IsSet)
                writer.WriteBoolean("audio_to_llm", preRecordedRequestParamsResponse.AudioToLlmOption.Value!.Value);

            if (preRecordedRequestParamsResponse.AudioToLlmConfigOption.IsSet)
            {
                writer.WritePropertyName("audio_to_llm_config");
                JsonSerializer.Serialize(writer, preRecordedRequestParamsResponse.AudioToLlmConfig, jsonSerializerOptions);
            }
            if (preRecordedRequestParamsResponse.SentencesOption.IsSet)
                writer.WriteBoolean("sentences", preRecordedRequestParamsResponse.SentencesOption.Value!.Value);

            if (preRecordedRequestParamsResponse.DisplayModeOption.IsSet)
                writer.WriteBoolean("display_mode", preRecordedRequestParamsResponse.DisplayModeOption.Value!.Value);

            if (preRecordedRequestParamsResponse.PunctuationEnhancedOption.IsSet)
                writer.WriteBoolean("punctuation_enhanced", preRecordedRequestParamsResponse.PunctuationEnhancedOption.Value!.Value);

            if (preRecordedRequestParamsResponse.LanguageConfigOption.IsSet)
            {
                writer.WritePropertyName("language_config");
                JsonSerializer.Serialize(writer, preRecordedRequestParamsResponse.LanguageConfig, jsonSerializerOptions);
            }
        }
    }
}
