// <auto-generated>
/*
 * Gladia Control API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Gladia.SDK.Client;

namespace Gladia.SDK.Model
{
    /// <summary>
    /// SpeechEndMessage
    /// </summary>
    public partial class SpeechEndMessage : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SpeechEndMessage" /> class.
        /// </summary>
        /// <param name="sessionId">Id of the live session</param>
        /// <param name="createdAt">Date of creation of the message. The date is formatted as an ISO 8601 string</param>
        /// <param name="data">The message data</param>
        /// <param name="type">type (default to TypeEnum.SpeechEnd)</param>
        [JsonConstructor]
        public SpeechEndMessage(string sessionId, string createdAt, SpeechMessageData data, TypeEnum type = TypeEnum.SpeechEnd)
        {
            SessionId = sessionId;
            CreatedAt = createdAt;
            Data = data;
            Type = type;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines Type
        /// </summary>
        public enum TypeEnum
        {
            /// <summary>
            /// Enum SpeechEnd for value: speech_end
            /// </summary>
            SpeechEnd = 1
        }

        /// <summary>
        /// Returns a <see cref="TypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static TypeEnum TypeEnumFromString(string value)
        {
            if (value.Equals("speech_end"))
                return TypeEnum.SpeechEnd;

            throw new NotImplementedException($"Could not convert value to type TypeEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="TypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static TypeEnum? TypeEnumFromStringOrDefault(string value)
        {
            if (value.Equals("speech_end"))
                return TypeEnum.SpeechEnd;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="TypeEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string TypeEnumToJsonValue(TypeEnum value)
        {
            if (value == TypeEnum.SpeechEnd)
                return "speech_end";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        /* <example>speech_end</example> */
        [JsonPropertyName("type")]
        public TypeEnum Type { get; set; }

        /// <summary>
        /// Id of the live session
        /// </summary>
        /// <value>Id of the live session</value>
        /* <example>4a39145c-2844-4557-8f34-34883f7be7d9</example> */
        [JsonPropertyName("session_id")]
        public string SessionId { get; set; }

        /// <summary>
        /// Date of creation of the message. The date is formatted as an ISO 8601 string
        /// </summary>
        /// <value>Date of creation of the message. The date is formatted as an ISO 8601 string</value>
        /* <example>2021-09-01T12:00:00.123Z</example> */
        [JsonPropertyName("created_at")]
        public string CreatedAt { get; set; }

        /// <summary>
        /// The message data
        /// </summary>
        /// <value>The message data</value>
        [JsonPropertyName("data")]
        public SpeechMessageData Data { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SpeechEndMessage {\n");
            sb.Append("  SessionId: ").Append(SessionId).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  Data: ").Append(Data).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SpeechEndMessage" />
    /// </summary>
    public class SpeechEndMessageJsonConverter : JsonConverter<SpeechEndMessage>
    {
        /// <summary>
        /// Deserializes json to <see cref="SpeechEndMessage" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override SpeechEndMessage Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> sessionId = default;
            Option<string?> createdAt = default;
            Option<SpeechMessageData?> data = default;
            Option<SpeechEndMessage.TypeEnum?> type = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "session_id":
                            sessionId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "created_at":
                            createdAt = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "data":
                            data = new Option<SpeechMessageData?>(JsonSerializer.Deserialize<SpeechMessageData>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "type":
                            string? typeRawValue = utf8JsonReader.GetString();
                            if (typeRawValue != null)
                                type = new Option<SpeechEndMessage.TypeEnum?>(SpeechEndMessage.TypeEnumFromStringOrDefault(typeRawValue));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!sessionId.IsSet)
                throw new ArgumentException("Property is required for class SpeechEndMessage.", nameof(sessionId));

            if (!createdAt.IsSet)
                throw new ArgumentException("Property is required for class SpeechEndMessage.", nameof(createdAt));

            if (!data.IsSet)
                throw new ArgumentException("Property is required for class SpeechEndMessage.", nameof(data));

            if (!type.IsSet)
                throw new ArgumentException("Property is required for class SpeechEndMessage.", nameof(type));

            if (sessionId.IsSet && sessionId.Value == null)
                throw new ArgumentNullException(nameof(sessionId), "Property is not nullable for class SpeechEndMessage.");

            if (createdAt.IsSet && createdAt.Value == null)
                throw new ArgumentNullException(nameof(createdAt), "Property is not nullable for class SpeechEndMessage.");

            if (data.IsSet && data.Value == null)
                throw new ArgumentNullException(nameof(data), "Property is not nullable for class SpeechEndMessage.");

            if (type.IsSet && type.Value == null)
                throw new ArgumentNullException(nameof(type), "Property is not nullable for class SpeechEndMessage.");

            return new SpeechEndMessage(sessionId.Value!, createdAt.Value!, data.Value!, type.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="SpeechEndMessage" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="speechEndMessage"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, SpeechEndMessage speechEndMessage, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, speechEndMessage, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="SpeechEndMessage" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="speechEndMessage"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, SpeechEndMessage speechEndMessage, JsonSerializerOptions jsonSerializerOptions)
        {
            if (speechEndMessage.SessionId == null)
                throw new ArgumentNullException(nameof(speechEndMessage.SessionId), "Property is required for class SpeechEndMessage.");

            if (speechEndMessage.CreatedAt == null)
                throw new ArgumentNullException(nameof(speechEndMessage.CreatedAt), "Property is required for class SpeechEndMessage.");

            if (speechEndMessage.Data == null)
                throw new ArgumentNullException(nameof(speechEndMessage.Data), "Property is required for class SpeechEndMessage.");

            writer.WriteString("session_id", speechEndMessage.SessionId);

            writer.WriteString("created_at", speechEndMessage.CreatedAt);

            writer.WritePropertyName("data");
            JsonSerializer.Serialize(writer, speechEndMessage.Data, jsonSerializerOptions);
            var typeRawValue = SpeechEndMessage.TypeEnumToJsonValue(speechEndMessage.Type);
            writer.WriteString("type", typeRawValue);
        }
    }
}
