// <auto-generated>
/*
 * Gladia Control API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Gladia.SDK.Client;

namespace Gladia.SDK.Model
{
    /// <summary>
    /// SubtitleDTO
    /// </summary>
    public partial class SubtitleDTO : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SubtitleDTO" /> class.
        /// </summary>
        /// <param name="format">Format of the current subtitle</param>
        /// <param name="subtitles">Transcription on the asked subtitle format</param>
        [JsonConstructor]
        public SubtitleDTO(SubtitlesFormatEnum format, string subtitles)
        {
            Format = format;
            Subtitles = subtitles;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Format of the current subtitle
        /// </summary>
        /// <value>Format of the current subtitle</value>
        [JsonPropertyName("format")]
        public SubtitlesFormatEnum Format { get; set; }

        /// <summary>
        /// Transcription on the asked subtitle format
        /// </summary>
        /// <value>Transcription on the asked subtitle format</value>
        [JsonPropertyName("subtitles")]
        public string Subtitles { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SubtitleDTO {\n");
            sb.Append("  Format: ").Append(Format).Append("\n");
            sb.Append("  Subtitles: ").Append(Subtitles).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SubtitleDTO" />
    /// </summary>
    public class SubtitleDTOJsonConverter : JsonConverter<SubtitleDTO>
    {
        /// <summary>
        /// Deserializes json to <see cref="SubtitleDTO" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override SubtitleDTO Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<SubtitlesFormatEnum?> format = default;
            Option<string?> subtitles = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "format":
                            string? formatRawValue = utf8JsonReader.GetString();
                            if (formatRawValue != null)
                                format = new Option<SubtitlesFormatEnum?>(SubtitlesFormatEnumValueConverter.FromStringOrDefault(formatRawValue));
                            break;
                        case "subtitles":
                            subtitles = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!format.IsSet)
                throw new ArgumentException("Property is required for class SubtitleDTO.", nameof(format));

            if (!subtitles.IsSet)
                throw new ArgumentException("Property is required for class SubtitleDTO.", nameof(subtitles));

            if (format.IsSet && format.Value == null)
                throw new ArgumentNullException(nameof(format), "Property is not nullable for class SubtitleDTO.");

            if (subtitles.IsSet && subtitles.Value == null)
                throw new ArgumentNullException(nameof(subtitles), "Property is not nullable for class SubtitleDTO.");

            return new SubtitleDTO(format.Value!.Value!, subtitles.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="SubtitleDTO" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="subtitleDTO"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, SubtitleDTO subtitleDTO, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, subtitleDTO, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="SubtitleDTO" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="subtitleDTO"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, SubtitleDTO subtitleDTO, JsonSerializerOptions jsonSerializerOptions)
        {
            if (subtitleDTO.Subtitles == null)
                throw new ArgumentNullException(nameof(subtitleDTO.Subtitles), "Property is required for class SubtitleDTO.");

            var formatRawValue = SubtitlesFormatEnumValueConverter.ToJsonValue(subtitleDTO.Format);
            writer.WriteString("format", formatRawValue);

            writer.WriteString("subtitles", subtitleDTO.Subtitles);
        }
    }
}
