// <auto-generated>
/*
 * Gladia Control API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Gladia.SDK.Client;

namespace Gladia.SDK.Model
{
    /// <summary>
    /// TranscriptMessageData
    /// </summary>
    public partial class TranscriptMessageData : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TranscriptMessageData" /> class.
        /// </summary>
        /// <param name="id">Id of the utterance</param>
        /// <param name="isFinal">Flag to indicate if the transcript is final or not</param>
        /// <param name="utterance">The transcribed utterance</param>
        [JsonConstructor]
        public TranscriptMessageData(string id, bool isFinal, UtteranceDTO utterance)
        {
            Id = id;
            IsFinal = isFinal;
            Utterance = utterance;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Id of the utterance
        /// </summary>
        /// <value>Id of the utterance</value>
        /* <example>00-00000011</example> */
        [JsonPropertyName("id")]
        public string Id { get; set; }

        /// <summary>
        /// Flag to indicate if the transcript is final or not
        /// </summary>
        /// <value>Flag to indicate if the transcript is final or not</value>
        /* <example>true</example> */
        [JsonPropertyName("is_final")]
        public bool IsFinal { get; set; }

        /// <summary>
        /// The transcribed utterance
        /// </summary>
        /// <value>The transcribed utterance</value>
        [JsonPropertyName("utterance")]
        public UtteranceDTO Utterance { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TranscriptMessageData {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  IsFinal: ").Append(IsFinal).Append("\n");
            sb.Append("  Utterance: ").Append(Utterance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="TranscriptMessageData" />
    /// </summary>
    public class TranscriptMessageDataJsonConverter : JsonConverter<TranscriptMessageData>
    {
        /// <summary>
        /// Deserializes json to <see cref="TranscriptMessageData" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override TranscriptMessageData Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> id = default;
            Option<bool?> isFinal = default;
            Option<UtteranceDTO?> utterance = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "is_final":
                            isFinal = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "utterance":
                            utterance = new Option<UtteranceDTO?>(JsonSerializer.Deserialize<UtteranceDTO>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class TranscriptMessageData.", nameof(id));

            if (!isFinal.IsSet)
                throw new ArgumentException("Property is required for class TranscriptMessageData.", nameof(isFinal));

            if (!utterance.IsSet)
                throw new ArgumentException("Property is required for class TranscriptMessageData.", nameof(utterance));

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class TranscriptMessageData.");

            if (isFinal.IsSet && isFinal.Value == null)
                throw new ArgumentNullException(nameof(isFinal), "Property is not nullable for class TranscriptMessageData.");

            if (utterance.IsSet && utterance.Value == null)
                throw new ArgumentNullException(nameof(utterance), "Property is not nullable for class TranscriptMessageData.");

            return new TranscriptMessageData(id.Value!, isFinal.Value!.Value!, utterance.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="TranscriptMessageData" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="transcriptMessageData"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, TranscriptMessageData transcriptMessageData, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, transcriptMessageData, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="TranscriptMessageData" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="transcriptMessageData"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, TranscriptMessageData transcriptMessageData, JsonSerializerOptions jsonSerializerOptions)
        {
            if (transcriptMessageData.Id == null)
                throw new ArgumentNullException(nameof(transcriptMessageData.Id), "Property is required for class TranscriptMessageData.");

            if (transcriptMessageData.Utterance == null)
                throw new ArgumentNullException(nameof(transcriptMessageData.Utterance), "Property is required for class TranscriptMessageData.");

            writer.WriteString("id", transcriptMessageData.Id);

            writer.WriteBoolean("is_final", transcriptMessageData.IsFinal);

            writer.WritePropertyName("utterance");
            JsonSerializer.Serialize(writer, transcriptMessageData.Utterance, jsonSerializerOptions);
        }
    }
}
