// <auto-generated>
/*
 * Gladia Control API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Gladia.SDK.Client;

namespace Gladia.SDK.Model
{
    /// <summary>
    /// TranslationDTO
    /// </summary>
    public partial class TranslationDTO : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TranslationDTO" /> class.
        /// </summary>
        /// <param name="success">The audio intelligence model succeeded to get a valid output</param>
        /// <param name="isEmpty">The audio intelligence model returned an empty value</param>
        /// <param name="execTime">Time audio intelligence model took to complete the task</param>
        /// <param name="error">&#x60;null&#x60; if &#x60;success&#x60; is &#x60;true&#x60;. Contains the error details of the failed model</param>
        /// <param name="results">List of translated transcriptions, one for each &#x60;target_languages&#x60;</param>
        [JsonConstructor]
        public TranslationDTO(bool success, bool isEmpty, decimal execTime, AddonErrorDTO error, List<TranslationResultDTO> results)
        {
            Success = success;
            IsEmpty = isEmpty;
            ExecTime = execTime;
            Error = error;
            Results = results;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// The audio intelligence model succeeded to get a valid output
        /// </summary>
        /// <value>The audio intelligence model succeeded to get a valid output</value>
        [JsonPropertyName("success")]
        public bool Success { get; set; }

        /// <summary>
        /// The audio intelligence model returned an empty value
        /// </summary>
        /// <value>The audio intelligence model returned an empty value</value>
        [JsonPropertyName("is_empty")]
        public bool IsEmpty { get; set; }

        /// <summary>
        /// Time audio intelligence model took to complete the task
        /// </summary>
        /// <value>Time audio intelligence model took to complete the task</value>
        [JsonPropertyName("exec_time")]
        public decimal ExecTime { get; set; }

        /// <summary>
        /// &#x60;null&#x60; if &#x60;success&#x60; is &#x60;true&#x60;. Contains the error details of the failed model
        /// </summary>
        /// <value>&#x60;null&#x60; if &#x60;success&#x60; is &#x60;true&#x60;. Contains the error details of the failed model</value>
        [JsonPropertyName("error")]
        public AddonErrorDTO Error { get; set; }

        /// <summary>
        /// List of translated transcriptions, one for each &#x60;target_languages&#x60;
        /// </summary>
        /// <value>List of translated transcriptions, one for each &#x60;target_languages&#x60;</value>
        [JsonPropertyName("results")]
        public List<TranslationResultDTO> Results { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TranslationDTO {\n");
            sb.Append("  Success: ").Append(Success).Append("\n");
            sb.Append("  IsEmpty: ").Append(IsEmpty).Append("\n");
            sb.Append("  ExecTime: ").Append(ExecTime).Append("\n");
            sb.Append("  Error: ").Append(Error).Append("\n");
            sb.Append("  Results: ").Append(Results).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="TranslationDTO" />
    /// </summary>
    public class TranslationDTOJsonConverter : JsonConverter<TranslationDTO>
    {
        /// <summary>
        /// Deserializes json to <see cref="TranslationDTO" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override TranslationDTO Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<bool?> success = default;
            Option<bool?> isEmpty = default;
            Option<decimal?> execTime = default;
            Option<AddonErrorDTO?> error = default;
            Option<List<TranslationResultDTO>?> results = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "success":
                            success = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "is_empty":
                            isEmpty = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "exec_time":
                            execTime = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "error":
                            error = new Option<AddonErrorDTO?>(JsonSerializer.Deserialize<AddonErrorDTO>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "results":
                            results = new Option<List<TranslationResultDTO>?>(JsonSerializer.Deserialize<List<TranslationResultDTO>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!success.IsSet)
                throw new ArgumentException("Property is required for class TranslationDTO.", nameof(success));

            if (!isEmpty.IsSet)
                throw new ArgumentException("Property is required for class TranslationDTO.", nameof(isEmpty));

            if (!execTime.IsSet)
                throw new ArgumentException("Property is required for class TranslationDTO.", nameof(execTime));

            if (!error.IsSet)
                throw new ArgumentException("Property is required for class TranslationDTO.", nameof(error));

            if (!results.IsSet)
                throw new ArgumentException("Property is required for class TranslationDTO.", nameof(results));

            if (success.IsSet && success.Value == null)
                throw new ArgumentNullException(nameof(success), "Property is not nullable for class TranslationDTO.");

            if (isEmpty.IsSet && isEmpty.Value == null)
                throw new ArgumentNullException(nameof(isEmpty), "Property is not nullable for class TranslationDTO.");

            if (execTime.IsSet && execTime.Value == null)
                throw new ArgumentNullException(nameof(execTime), "Property is not nullable for class TranslationDTO.");

            if (error.IsSet && error.Value == null)
                throw new ArgumentNullException(nameof(error), "Property is not nullable for class TranslationDTO.");

            if (results.IsSet && results.Value == null)
                throw new ArgumentNullException(nameof(results), "Property is not nullable for class TranslationDTO.");

            return new TranslationDTO(success.Value!.Value!, isEmpty.Value!.Value!, execTime.Value!.Value!, error.Value!, results.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="TranslationDTO" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="translationDTO"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, TranslationDTO translationDTO, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, translationDTO, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="TranslationDTO" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="translationDTO"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, TranslationDTO translationDTO, JsonSerializerOptions jsonSerializerOptions)
        {
            if (translationDTO.Error == null)
                throw new ArgumentNullException(nameof(translationDTO.Error), "Property is required for class TranslationDTO.");

            if (translationDTO.Results == null)
                throw new ArgumentNullException(nameof(translationDTO.Results), "Property is required for class TranslationDTO.");

            writer.WriteBoolean("success", translationDTO.Success);

            writer.WriteBoolean("is_empty", translationDTO.IsEmpty);

            writer.WriteNumber("exec_time", translationDTO.ExecTime);

            writer.WritePropertyName("error");
            JsonSerializer.Serialize(writer, translationDTO.Error, jsonSerializerOptions);
            writer.WritePropertyName("results");
            JsonSerializer.Serialize(writer, translationDTO.Results, jsonSerializerOptions);
        }
    }
}
