// <auto-generated>
/*
 * Gladia Control API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Gladia.SDK.Client;

namespace Gladia.SDK.Model
{
    /// <summary>
    /// WebhookTranscriptionErrorPayload
    /// </summary>
    public partial class WebhookTranscriptionErrorPayload : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WebhookTranscriptionErrorPayload" /> class.
        /// </summary>
        /// <param name="payload">payload</param>
        /// <param name="event">event (default to EventEnum.TranscriptionError)</param>
        [JsonConstructor]
        public WebhookTranscriptionErrorPayload(PreRecordedEventPayload payload, EventEnum @event = EventEnum.TranscriptionError)
        {
            Payload = payload;
            Event = @event;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines Event
        /// </summary>
        public enum EventEnum
        {
            /// <summary>
            /// Enum TranscriptionError for value: transcription.error
            /// </summary>
            TranscriptionError = 1
        }

        /// <summary>
        /// Returns a <see cref="EventEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static EventEnum EventEnumFromString(string value)
        {
            if (value.Equals("transcription.error"))
                return EventEnum.TranscriptionError;

            throw new NotImplementedException($"Could not convert value to type EventEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="EventEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static EventEnum? EventEnumFromStringOrDefault(string value)
        {
            if (value.Equals("transcription.error"))
                return EventEnum.TranscriptionError;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="EventEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string EventEnumToJsonValue(EventEnum value)
        {
            if (value == EventEnum.TranscriptionError)
                return "transcription.error";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Gets or Sets Event
        /// </summary>
        /* <example>transcription.error</example> */
        [JsonPropertyName("event")]
        public EventEnum Event { get; set; }

        /// <summary>
        /// Gets or Sets Payload
        /// </summary>
        [JsonPropertyName("payload")]
        public PreRecordedEventPayload Payload { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WebhookTranscriptionErrorPayload {\n");
            sb.Append("  Payload: ").Append(Payload).Append("\n");
            sb.Append("  Event: ").Append(Event).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="WebhookTranscriptionErrorPayload" />
    /// </summary>
    public class WebhookTranscriptionErrorPayloadJsonConverter : JsonConverter<WebhookTranscriptionErrorPayload>
    {
        /// <summary>
        /// Deserializes json to <see cref="WebhookTranscriptionErrorPayload" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override WebhookTranscriptionErrorPayload Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<PreRecordedEventPayload?> payload = default;
            Option<WebhookTranscriptionErrorPayload.EventEnum?> varEvent = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "payload":
                            payload = new Option<PreRecordedEventPayload?>(JsonSerializer.Deserialize<PreRecordedEventPayload>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "event":
                            string? varEventRawValue = utf8JsonReader.GetString();
                            if (varEventRawValue != null)
                                varEvent = new Option<WebhookTranscriptionErrorPayload.EventEnum?>(WebhookTranscriptionErrorPayload.EventEnumFromStringOrDefault(varEventRawValue));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!payload.IsSet)
                throw new ArgumentException("Property is required for class WebhookTranscriptionErrorPayload.", nameof(payload));

            if (!varEvent.IsSet)
                throw new ArgumentException("Property is required for class WebhookTranscriptionErrorPayload.", nameof(varEvent));

            if (payload.IsSet && payload.Value == null)
                throw new ArgumentNullException(nameof(payload), "Property is not nullable for class WebhookTranscriptionErrorPayload.");

            if (varEvent.IsSet && varEvent.Value == null)
                throw new ArgumentNullException(nameof(varEvent), "Property is not nullable for class WebhookTranscriptionErrorPayload.");

            return new WebhookTranscriptionErrorPayload(payload.Value!, varEvent.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="WebhookTranscriptionErrorPayload" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="webhookTranscriptionErrorPayload"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, WebhookTranscriptionErrorPayload webhookTranscriptionErrorPayload, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, webhookTranscriptionErrorPayload, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="WebhookTranscriptionErrorPayload" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="webhookTranscriptionErrorPayload"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, WebhookTranscriptionErrorPayload webhookTranscriptionErrorPayload, JsonSerializerOptions jsonSerializerOptions)
        {
            if (webhookTranscriptionErrorPayload.Payload == null)
                throw new ArgumentNullException(nameof(webhookTranscriptionErrorPayload.Payload), "Property is required for class WebhookTranscriptionErrorPayload.");

            writer.WritePropertyName("payload");
            JsonSerializer.Serialize(writer, webhookTranscriptionErrorPayload.Payload, jsonSerializerOptions);
            var varEventRawValue = WebhookTranscriptionErrorPayload.EventEnumToJsonValue(webhookTranscriptionErrorPayload.Event);
            writer.WriteString("event", varEventRawValue);
        }
    }
}
