name: Test SDK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/test-sdk.yml
    with:
      node-versions: '[18, 19, 20, 21, 22]'
      upload-coverage: 'true' 