name: Test SDK (Reusable)

on:
  workflow_call:
    inputs:
      node-versions:
        description: 'Node.js versions to test against'
        required: false
        default: '[18, 19, 20, 21, 22]'
        type: string
      upload-coverage:
        description: 'Whether to upload coverage artifacts'
        required: false
        default: 'true'
        type: string

jobs:
  test:
    strategy:
      matrix:
        node-version: ${{ fromJson(inputs.node-versions) }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Build SDK
        run: pnpm build

      - name: Run tests
        run: pnpm test

      - name: Run linting
        run: pnpm lint

      - name: Check test coverage
        if: inputs.upload-coverage == 'true'
        run: pnpm test:coverage

      - name: Upload coverage artifacts
        if: inputs.upload-coverage == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.node-version }}
          path: coverage/
          retention-days: 30

